from retrieval.hybrid_retriever import HybridRetriever
from retrieval.query_enrichment import enrich_financial_query
from retrieval.retrieval_context import RetrievalContext
from storage.vector_models import SearchResult


class _Embedding(list):
    def tolist(self):
        return list(self)


class _CapturingModel:
    def __init__(self):
        self.inputs: list[str] = []

    def encode(
        self,
        text,
        convert_to_tensor=False,
        normalize_embeddings=False,
    ):
        del convert_to_tensor, normalize_embeddings
        self.inputs.append(text)
        return _Embedding([0.1, 0.2])


class _Store:
    def __init__(self, documents):
        self.documents = documents

    def similarity_search(self, *, query_embedding, top_k, tenant_id):
        del query_embedding, tenant_id
        return self.documents[:top_k]

    def lexical_corpus(self, tenant_id=None):
        del tenant_id
        return self.documents


def _result(chunk_id: str, content: str) -> SearchResult:
    return SearchResult(
        document_id="tesla-q2",
        chunk_id=chunk_id,
        score=0.2,
        content=content,
        metadata={
            "tenant_id": 7,
            "company": "Tesla",
            "source": "Tesla_Q2_2025.pdf",
        },
    )


def test_chinese_financial_query_adds_auditable_english_hints():
    enriched = enrich_financial_query(
        "特斯拉2025年第二季度汽车业务收入增长多少？",
        "Tesla",
    )

    assert enriched.startswith("特斯拉2025年第二季度")
    assert enriched.count("Tesla") == 1
    assert "Q2 second quarter" in enriched
    assert "automotive" in enriched
    assert "revenue" in enriched
    assert "growth" in enriched


def test_non_financial_english_query_is_not_rewritten():
    question = "What is AI?"

    assert enrich_financial_query(question) == question


def test_english_financial_query_adds_exact_table_terms():
    enriched = enrich_financial_query(
        "Analyze Tesla Q2 2025 automotive revenue growth.",
        "Tesla",
    )

    assert enriched.startswith(
        "Analyze Tesla Q2 2025 automotive revenue growth."
    )
    assert "Q2-2025" in enriched
    assert "Q2'25" in enriched
    assert "total automotive revenues" in enriched
    assert "quarterly total revenues" in enriched


def test_chinese_financial_summary_adds_headline_metric_terms():
    enriched = enrich_financial_query("总结苹果公司 2026 年第二季度的财务表现。", "Apple")

    assert "net sales" in enriched
    assert "net income" in enriched
    assert "operating cash flow" in enriched


def test_chinese_revenue_performance_adds_quarterly_sales_table_terms():
    enriched = enrich_financial_query("苹果 2026 年第二季度财报中的营收表现如何？", "Apple")

    assert "financial summary" in enriched
    assert "quarterly total net sales" in enriched
    assert "total revenues" in enriched


def test_bilingual_financial_summary_paraphrases_share_structural_filing_terms():
    english = enrich_financial_query(
        "Summarize Tesla's financial performance in Q2 2025.", "Tesla"
    )
    chinese = enrich_financial_query("总结特斯拉 2025 年第二季度的财务表现。", "Tesla")

    shared_terms = (
        "financial summary",
        "total net sales",
        "total revenues",
        "net income",
        "gross margin",
        "operating cash flow",
    )
    assert all(term in english for term in shared_terms)
    assert all(term in chinese for term in shared_terms)


def test_chinese_cash_flow_and_automotive_terms_match_english_filing_labels():
    cash_flow = enrich_financial_query("苹果 2026 年第二季度财报如何描述现金流情况？", "Apple")
    automotive = enrich_financial_query("TSLA 的汽车业务最近表现如何？", "Tesla")

    assert "cash generated by operating activities" in cash_flow
    assert "automotive revenue" in automotive
    assert "total automotive revenues" in automotive


def test_chinese_segment_questions_add_the_same_filing_terms_as_english():
    data_center = enrich_financial_query(
        "英伟达 2027 财年第一季度的数据中心业务表现如何？", "NVIDIA"
    )
    edge = enrich_financial_query("英伟达最新报告中的边缘计算业务如何？", "NVIDIA")

    assert "Data Center revenue" in data_center
    assert "data center performance" in data_center
    assert "Edge Computing revenue" in edge
    assert "edge computing performance" in edge


def test_chinese_comparison_adds_column_aware_financial_summary_terms():
    enriched = enrich_financial_query("比较特斯拉和英伟达的营收表现。")

    assert "financial summary" in enriched
    assert "quarterly total revenues" in enriched


def test_english_financial_performance_comparison_adds_same_structural_terms():
    enriched = enrich_financial_query(
        "Compare Apple and Tesla's financial performance."
    )

    assert "financial summary" in enriched
    assert "quarterly total revenues" in enriched


def test_fiscal_quarter_adds_exact_filing_period_aliases():
    enriched = enrich_financial_query(
        "英伟达2027财年第一季度毛利率是多少？",
        "NVIDIA",
    )

    assert "Q1 FY27" in enriched
    assert "Q1 Fiscal 2027" in enriched
    assert "gross margin" in enriched


def test_hybrid_retrieval_uses_enriched_query_for_embedding_and_bm25():
    generic = _result("generic", "Tesla product and delivery overview.")
    financial = _result(
        "financial",
        "Q2 total automotive revenue increased year over year.",
    )
    model = _CapturingModel()

    results = HybridRetriever(model).retrieve(
        RetrievalContext(
            question="特斯拉第二季度汽车业务收入增长如何？",
            company="Tesla",
            tenant_id=7,
            top_k=2,
        ),
        _Store([generic, financial]),
    )

    assert model.inputs
    assert model.inputs[0].startswith("query: 特斯拉第二季度")
    assert "automotive" in model.inputs[0]
    assert "revenue" in model.inputs[0]
    assert results[0].chunk_id == "financial"
    assert results[0].metadata["bm25_rank"] == 1
    assert results[0].metadata["lexical_weight"] == 1.25
