from agent.reasoning_models import Evidence
from core.query_scope import QueryScope
from core.retrieval_probes import retrieval_probe_queries, retrieval_probe_top_k


def test_financial_summary_keeps_bounded_headline_probes_in_both_languages():
    english = retrieval_probe_queries(
        "Summarize NVIDIA's financial performance in Q1 FY2027.",
        QueryScope.SUMMARY,
    )
    chinese = retrieval_probe_queries(
        "总结英伟达 2027 财年第一季度的财务表现。",
        QueryScope.SUMMARY,
    )

    expected = {
        "NVIDIA total revenues Q1_FY2027",
        "NVIDIA net income Q1_FY2027",
        "NVIDIA gross profit Q1_FY2027",
        "NVIDIA gross margin Q1_FY2027",
        "NVIDIA operating margin Q1_FY2027",
        "NVIDIA cash generated by operating activities Q1_FY2027",
        "NVIDIA net cash provided by operating activities Q1_FY2027",
        "NVIDIA eps Q1_FY2027",
    }
    assert expected <= set(english)
    assert expected <= set(chinese)


def test_revenue_performance_summaries_use_company_period_fact_probes():
    english = set(retrieval_probe_queries(
        "What does Apple's Q2 2026 report say about revenue performance?",
        QueryScope.SUMMARY,
    ))
    chinese = set(retrieval_probe_queries(
        "苹果 2026 年第二季度财报中的营收表现如何？",
        QueryScope.SUMMARY,
    ))
    expected = {
        "Apple total revenues Q2_2026",
        "Apple net income Q2_2026",
        "Apple gross profit Q2_2026",
        "Apple eps Q2_2026",
    }

    assert expected <= english
    assert expected <= chinese


def test_narrative_business_development_does_not_probe_unrequested_financial_tables():
    questions = (
        "Summarize Tesla's major business developments during Q2 2025.",
        "总结特斯拉 2025 年第二季度的主要业务发展。",
    )
    for question in questions:
        probes = retrieval_probe_queries(question, QueryScope.SUMMARY)
        assert all("financial summary" not in query for query in probes)
        assert all(not query.endswith(("revenue", "net income", "earnings per share")) for query in probes)
        assert all("segment revenue growth drivers" not in query for query in probes)


def test_bilingual_comparisons_share_company_scoped_metric_probes():
    english = retrieval_probe_queries(
        "Compare Tesla and NVIDIA revenue performance.", QueryScope.COMPARE
    )
    chinese = retrieval_probe_queries(
        "比较特斯拉和英伟达的营收表现。", QueryScope.COMPARE
    )
    company_metric_probes = {"Tesla total revenues", "NVIDIA total revenues"}

    assert company_metric_probes <= set(english)
    assert company_metric_probes <= set(chinese)


def test_growth_narrative_comparison_probes_headline_and_growth_for_each_issuer():
    evidence = [
        Evidence(
            content="Apple Q2 FY2026 filing excerpt.",
            source="Apple.pdf",
            company="Apple",
            metadata={"quarter": "Q2_FY2026", "chunk_id": "apple-q2"},
        ),
        Evidence(
            content="NVIDIA Q1 FY2027 filing excerpt.",
            source="NVIDIA.pdf",
            company="NVIDIA",
            metadata={"quarter": "Q1_FY2027", "chunk_id": "nvidia-q1"},
        ),
        Evidence(
            content="Tesla Q4 2025 filing excerpt.",
            source="Tesla.pdf",
            company="Tesla",
            metadata={"quarter": "Q4_2025", "chunk_id": "tesla-q4"},
        ),
    ]
    for question in (
        "Which of Apple, NVIDIA and Tesla reports the strongest growth narrative?",
        "苹果、英伟达和特斯拉中，哪一家财报体现出的增长势头最强？",
    ):
        probes = set(retrieval_probe_queries(question, QueryScope.COMPARE, evidence))
        assert {
            "Apple total revenues Q2_FY2026",
            "Apple revenue growth Q2_FY2026",
            "NVIDIA total revenues Q1_FY2027",
            "NVIDIA revenue growth Q1_FY2027",
            "Tesla total revenues Q4_2025",
            "Tesla revenue growth Q4_2025",
        } <= probes


def test_segment_comparison_probes_cover_verified_category_and_margin_rows():
    english = set(retrieval_probe_queries(
        "Compare Apple and NVIDIA's major business segments.", QueryScope.COMPARE
    ))
    chinese = set(retrieval_probe_queries(
        "比较苹果和英伟达的主要业务分部。", QueryScope.COMPARE
    ))

    expected = {
        "Apple iphone®",
        "Apple mac®",
        "Apple ipad®",
        "Apple wearables, home and accessories",
        "Apple products gross margin",
        "Apple services gross margin",
        "NVIDIA data center revenue",
    }
    assert expected <= english
    assert expected <= chinese


def test_bilingual_financial_comparison_has_identical_per_company_summary_probes():
    english = set(retrieval_probe_queries(
        "Compare Apple and Tesla's financial performance.", QueryScope.COMPARE
    ))
    chinese = set(retrieval_probe_queries(
        "比较苹果和特斯拉的财务表现。", QueryScope.COMPARE
    ))
    expected = {"Apple financial summary", "Tesla financial summary"}
    expected_metric_probes = {
        f"{company} {metric}"
        for company in ("Apple", "Tesla")
        for metric in (
            "total revenues",
            "net income",
            "gross margin",
            "operating margin",
            "cash generated by operating activities",
            "eps",
        )
    }

    assert expected <= english
    assert expected <= chinese
    assert expected_metric_probes <= english
    assert expected_metric_probes <= chinese


def test_bilingual_single_company_financial_summaries_share_metric_probe_terms():
    english = set(retrieval_probe_queries(
        "How was the iPhone maker doing financially in the second quarter of 2026?",
        QueryScope.SUMMARY,
    ))
    chinese = set(retrieval_probe_queries(
        "那个做 iPhone 的公司 2026 年二季度业绩怎么样？",
        QueryScope.SUMMARY,
    ))
    expected = {
        "Apple total revenues Q2_2026",
        "Apple net income Q2_2026",
        "Apple gross margin Q2_2026",
        "Apple operating margin Q2_2026",
        "Apple cash generated by operating activities Q2_2026",
        "Apple eps Q2_2026",
    }

    assert expected <= english
    assert expected <= chinese


def test_bilingual_implicit_ev_maker_summary_uses_same_company_period_probes():
    english = set(retrieval_probe_queries(
        "How did the EV maker perform financially in the second quarter of 2025?",
        QueryScope.SUMMARY,
    ))
    chinese = set(retrieval_probe_queries(
        "那家电动车公司在 2025 年二季度经营得怎么样？",
        QueryScope.SUMMARY,
    ))
    expected = {
        "Tesla total revenues Q2_2025",
        "Tesla total automotive revenues Q2_2025",
        "Tesla services net sales Q2_2025",
        "Tesla net income Q2_2025",
        "Tesla gross margin Q2_2025",
        "Tesla operating margin Q2_2025",
        "Tesla cash generated by operating activities Q2_2025",
        "Tesla eps Q2_2025",
        "Tesla net income attributable to common stockholders Q2_2025",
        "Tesla earnings per share Q2_2025",
    }

    assert expected <= english
    assert expected <= chinese


def test_financial_summary_probes_only_missing_requested_period_metrics():
    evidence = [
        Evidence(
            content="Apple Q2 2026 total revenue was $111,184 million.",
            source="Apple.pdf",
            company="Apple",
            metadata={"quarter": "Q2_2026", "chunk_id": "apple-revenue"},
        )
    ]
    probes = retrieval_probe_queries(
        "Summarize Apple's financial performance in Q2 2026.",
        QueryScope.SUMMARY,
        evidence,
    )

    assert "Apple total revenues Q2_2026" not in probes
    assert "Apple gross margin Q2_2026" in probes
    assert "Apple cash generated by operating activities Q2_2026" in probes
    assert "Apple earnings per share Q2_2026" in probes


def test_unscoped_summary_does_not_skip_metrics_found_for_an_unrelated_period():
    evidence = [
        Evidence(
            content="Tesla Q2 2025 net income was $1.172 billion.",
            source="Tesla.pdf",
            company="Tesla",
            metadata={"quarter": "Q2_2025", "chunk_id": "tesla-q2-net-income"},
        )
    ]
    probes = retrieval_probe_queries(
        "Compare Tesla and NVIDIA's financial performance.",
        QueryScope.COMPARE,
        evidence,
    )

    assert "Tesla net income Q2_2025" in probes
    assert "Tesla net income attributable to common stockholders Q2_2025" in probes


def test_bilingual_implicit_comparison_uses_each_observed_company_filing_period():
    english_evidence = [
        Evidence(
            content="Tesla Q4 2025 filing excerpt.",
            source="Tesla.pdf",
            company="Tesla",
            metadata={"quarter": "Q4_2025", "document_reporting_period": "Q4_2025", "chunk_id": "tesla-q4"},
        ),
        Evidence(
            content="NVIDIA Q1 FY2027 filing excerpt.",
            source="NVIDIA.pdf",
            company="NVIDIA",
            metadata={"quarter": "Q1_FY2027", "document_reporting_period": "Q1_FY2027", "chunk_id": "nvidia-q1"},
        ),
    ]
    chinese_evidence = [
        Evidence(
            content="特斯拉当前财报片段。",
            source="Tesla.pdf",
            company="Tesla",
            metadata={"quarter": "Q4_2025", "document_reporting_period": "Q4_2025", "chunk_id": "tesla-q4"},
        ),
        Evidence(
            content="英伟达当前财报片段。",
            source="NVIDIA.pdf",
            company="NVIDIA",
            metadata={"quarter": "Q1_FY2027", "document_reporting_period": "Q1_FY2027", "chunk_id": "nvidia-q1"},
        ),
    ]
    english = set(retrieval_probe_queries(
        "Compare Tesla and NVIDIA revenue performance.",
        QueryScope.COMPARE,
        english_evidence,
    ))
    chinese = set(retrieval_probe_queries(
        "比较特斯拉和英伟达的营收表现。",
        QueryScope.COMPARE,
        chinese_evidence,
    ))

    expected = {
        "Tesla total revenues Q4_2025",
        "NVIDIA total revenues Q1_FY2027",
    }
    assert expected <= english
    assert expected <= chinese


def test_canonical_company_metric_probe_uses_deeper_bounded_top_k():
    assert retrieval_probe_top_k(
        "Compare Apple and Tesla revenue performance.", "Tesla total revenues"
    ) == 8
    assert retrieval_probe_top_k(
        "Summarize Tesla financial performance.",
        "Summarize Tesla financial performance. financial summary",
    ) == 3


def test_causal_financial_change_probes_use_observed_company_context():
    question = "年报中2025年经营活动现金流净额下降主要归因于什么？"
    row = Evidence(
        content=(
            "Structured financial table row — Metric: Operating Cash Flow | "
            "FY2025: 61522204989.35 CNY | FY2024: 92463692168.43 CNY"
        ),
        source="贵州茅台_2025年度报告.pdf",
        company="贵州茅台",
        metadata={
            "content_type": "table",
            "quarter": "2025-12-31",
            "chunk_id": "moutai-cash-flow-row",
        },
    )

    probes = retrieval_probe_queries(
        question,
        QueryScope.ANALYSIS,
        [row],
    )

    assert any(
        "贵州茅台" in probe
        and "经营活动产生的现金流量净额" in probe
        and "变化原因" in probe
        and "2025" in probe
        for probe in probes
    )
