"""Provider-free required-fact coverage for financial answers.

Retrieval recall alone does not prove that an answer contains the facts a
question requires.  This module derives a small, scope-aware set of required
facts from the query and checks whether the final evidence and answer retain
them.  It deliberately uses semantic labels rather than benchmark IDs or
question strings.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Iterable

from agent.planning.entity_extractor import extract_companies
from agent.reasoning_models import Evidence
from core.financial_grounding import canonical_metric, extract_normalized_numbers
from core.query_scope import (
    QueryScope,
    classify_query_scope,
    is_nonfinancial_business_development_summary,
)
from retrieval.periods import extract_metrics, extract_periods, period_scoped_row_numbers


@dataclass(frozen=True)
class RequiredFact:
    metric: str
    company: str | None = None
    period: str | None = None


@dataclass(frozen=True)
class FactCoverage:
    fact: RequiredFact
    evidence_present: bool
    answer_present: bool


@dataclass(frozen=True)
class CoverageResult:
    scope: str
    required: tuple[RequiredFact, ...]
    facts: tuple[FactCoverage, ...]

    @property
    def covered_count(self) -> int:
        return sum(item.evidence_present for item in self.facts)

    @property
    def answered_count(self) -> int:
        return sum(item.answer_present for item in self.facts)

    @property
    def grade(self) -> str:
        if not self.required:
            return "FULL"
        if self.answered_count == len(self.required):
            return "FULL"
        if self.answered_count or self.covered_count:
            return "PARTIAL"
        return "FAILED"

    def as_dict(self) -> dict[str, object]:
        return {
            "scope": self.scope,
            "grade": self.grade,
            "required": [fact.__dict__ for fact in self.required],
            "facts": [
                {
                    "metric": item.fact.metric,
                    "company": item.fact.company,
                    "period": item.fact.period,
                    "evidence_present": item.evidence_present,
                    "answer_present": item.answer_present,
                }
                for item in self.facts
            ],
        }


def _company_matches(evidence: Evidence, company: str | None) -> bool:
    if not company:
        return True
    aliases = {
        "nvidia": {"nvidia", "英伟达", "nvda"},
        "apple": {"apple", "苹果"},
        "tesla": {"tesla", "特斯拉"},
        "microsoft": {"microsoft", "微软"},
    }
    wanted = aliases.get(company.casefold(), {company.casefold()})
    actual = str(evidence.company or evidence.metadata.get("company", "")).casefold()
    return actual in wanted


def _period_matches(evidence: Evidence, period: str | None) -> bool:
    if not period:
        return True
    metadata = evidence.metadata
    values = set(str(metadata.get("periods", "")).split("|"))
    values.update(str(metadata.get("quarter", "")).replace("-", "_").split("|"))
    if period in values:
        return True
    return period in extract_periods(evidence.content)


def _financial_values(item: Evidence) -> list:
    values = extract_normalized_numbers(item.content)
    if not values:
        return []
    text = item.content.casefold()
    if re.search(r"\$|usd|million|billion|thousand|\u4ebf|\u4e07|\u5143|%", text):
        return values
    return [value for value in values if abs(value.value) >= 100]


def _fact_values(item: Evidence, metric: str) -> list:
    aliases = {
        "revenue": ("total net sales", "total revenues", "total revenue", "net sales"),
        "net_income": ("net income", "net profit"),
        "eps": ("diluted earnings per share", "basic earnings per share", "earnings per share"),
        "operating_cash_flow": ("cash generated by operating activities", "operating cash flow"),
        "cash_flow": ("cash generated by operating activities", "operating cash flow"),
        "data_center_revenue": ("data center revenue", "datacenter revenue"),
    }
    lowered = item.content.casefold()
    if metric in {"cash_flow", "operating_cash_flow"}:
        match = re.search(
            r"cash generated by operating activities\s*[:\n]?\s*([$\(\-]?\d[\d,]*(?:\.\d+)?)",
            lowered,
        )
        if match:
            start = match.start()
            values = extract_normalized_numbers(item.content[start : start + 120])
            values = [value for value in values if value.kind == "amount"]
            if values:
                return values
        return []
    for alias in aliases.get(metric, ()):
        position = lowered.find(alias.casefold())
        if position < 0:
            continue
        values = extract_normalized_numbers(item.content[position : position + 300])
        values = [value for value in values if value.kind in {"amount", "percent"}]
        if metric in {"revenue", "net_income", "cash_flow", "data_center_revenue"}:
            values = [value for value in values if value.kind == "amount"]
        values = [
            value
            for value in values
            if abs(value.value) >= 100
            or value.currency
            or any(marker in item.content.casefold() for marker in ("million", "billion", "\u4ebf", "\u4e07"))
        ]
        if metric == "eps":
            values = [value for value in values if value.currency or abs(value.value) < 10]
        if values:
            return values
    if metric == "eps":
        return []
    fallback = _financial_values(item)
    if metric in {"revenue", "net_income", "cash_flow", "data_center_revenue"}:
        fallback = [value for value in fallback if value.kind == "amount"]
    return fallback


def _select_fact_value(item: Evidence, fact: RequiredFact):
    period = fact.period or str(item.metadata.get("quarter", "")).replace("-", "_")
    scoped = period_scoped_row_numbers(item.content, period, fact.metric) if period else []
    if scoped:
        return scoped[0]
    if not fact.period and period and not extract_periods(item.content):
        return None
    values = _fact_values(item, fact.metric)
    return values[0] if values else None


def _metric_matches_content(metric: str, content: str) -> bool:
    text = content.casefold()
    if metric == "cash_flow":
        return any(
            token in text
            for token in ("cash generated by operating activities", "operating cash flow", "经营活动产生的现金流")
        )
    if metric == "net_income":
        return bool(re.search(r"(?:^|[\n:])\s*net income(?:\s|\$|:)", text))
    return metric in extract_metrics(content) or canonical_metric(content) == metric


def _answer_has_supported_metric(
    answer: str,
    fact: RequiredFact,
    items: list[Evidence],
    aliases: tuple[str, ...],
) -> bool:
    for line in str(answer or "").splitlines():
        lowered = line.casefold()
        if not any(alias in lowered for alias in aliases):
            continue
        claim_values = extract_normalized_numbers(line)
        if not claim_values:
            continue
        for item in items:
            if not _company_matches(item, fact.company) or not _period_matches(item, fact.period):
                continue
            if not _metric_matches_content(fact.metric, item.content):
                continue
            metadata_period = str(item.metadata.get("quarter", "")).replace("-", "_")
            periods = extract_periods(line) or ([metadata_period] if metadata_period else [])
            scoped = period_scoped_row_numbers(item.content, periods[0], fact.metric) if len(periods) == 1 else []
            if not scoped and periods and periods[0] not in extract_periods(item.content) and fact.period is None:
                continue
            values = scoped or _fact_values(item, fact.metric)
            if any(left.kind == right.kind and left.value == right.value for left in claim_values for right in values):
                return True
    return False


def infer_required_facts(question: str, evidence: Iterable[Evidence]) -> tuple[RequiredFact, ...]:
    """Infer stable requirements from scope, company and explicit period.

    Summary queries receive only the generic headline metrics (revenue, net
    income, EPS) that are actually represented by the financial corpus.  This
    avoids a fixed benchmark answer while still detecting a summary that
    discarded the headline table entirely.
    """

    scope = classify_query_scope(question)
    if is_nonfinancial_business_development_summary(question):
        # Narrative business-update requests have no implicit financial metric
        # checklist. Evaluating them against headline revenue/profit rows would
        # reward unrelated numeric over-answering.
        return ()
    companies = extract_companies(question)
    periods = extract_periods(question)
    period = periods[0] if periods else None
    metrics = [canonical_metric(question)] if canonical_metric(question) else []
    if scope == QueryScope.GENERAL_CONCEPT:
        return ()
    if scope == QueryScope.FACT and metrics:
        return tuple(RequiredFact(metrics[0], companies[0] if companies else None, period) for _ in [0])
    if scope == QueryScope.COMPARE:
        metric = metrics[0] if metrics else "revenue"
        return tuple(RequiredFact(metric, company, period) for company in companies)
    if scope == QueryScope.SUMMARY:
        headline = ["revenue", "net_income", "eps"]
        # Keep requirements generic but only when the corpus uses the metric
        # vocabulary; this is a semantic rule, not a question-ID allowlist.
        available = set()
        for item in evidence:
            available.update(extract_metrics(item.content))
        return tuple(
            RequiredFact(metric, companies[0] if companies else None, period)
            for metric in headline
            if metric in available or metric == "revenue"
        )
    return ()


def evaluate_coverage(
    question: str,
    answer: str,
    evidence: Iterable[Evidence],
) -> CoverageResult:
    items = list(evidence)
    required = infer_required_facts(question, items)
    facts: list[FactCoverage] = []
    for fact in required:
        matching = [
            item
            for item in items
            if _company_matches(item, fact.company)
            and _period_matches(item, fact.period)
            and _metric_matches_content(fact.metric, item.content)
        ]
        numeric_matching = [item for item in matching if _fact_values(item, fact.metric)]
        aliases = {
            "revenue": ("revenue", "revenues", "营收", "收入", "net sales"),
            "net_income": ("net income", "净利润", "net profit"),
            "eps": ("eps", "earnings per share", "每股收益"),
            "cash_flow": ("cash flow", "operating cash", "cash generated by operating", "现金流"),
            "operating_cash_flow": ("cash flow", "operating cash", "cash generated by operating", "经营活动现金流"),
            "data_center_revenue": ("data center", "datacenter", "数据中心"),
        }
        answer_present = _answer_has_supported_metric(
            answer,
            fact,
            numeric_matching,
            aliases.get(fact.metric, (fact.metric,)),
        )
        facts.append(FactCoverage(fact, bool(numeric_matching), answer_present))
    return CoverageResult(classify_query_scope(question).value, required, tuple(facts))


def _render_fact_value(value) -> str:
    if value.kind == "percent":
        return f"{value.value.normalize()}%"
    if value.kind == "basis_points":
        return f"{value.value.normalize()} bps"
    amount = value.value
    if amount % 1_000_000_000 == 0:
        return f"${(amount / 1_000_000_000).normalize()}B"
    if amount >= 1_000_000:
        return f"{amount / 1_000_000:,.0f} million"
    return f"{amount.normalize():,}"


def complete_answer_with_covered_facts(
    question: str,
    answer: str,
    evidence: Iterable[Evidence],
) -> tuple[str, CoverageResult, int]:
    """Append only evidence-backed required facts omitted by the model.

    This is a conservative coverage repair: it never invents a value and it
    does not run for concept/direct-chat questions.  A summary that says “the
    filing lacks revenue” while the final context contains a labelled revenue
    row therefore receives a short evidence-backed correction instead of a
    hallucinated expansion.
    """

    items = list(evidence)
    result = evaluate_coverage(question, answer, items)
    if not result.required:
        return answer, result, 0
    additions: list[str] = []
    labels = {
        "revenue": ("营收" if any("\u3400" <= char <= "\u9fff" for char in question) else "revenue"),
        "net_income": ("净利润" if any("\u3400" <= char <= "\u9fff" for char in question) else "net income"),
        "eps": ("每股收益" if any("\u3400" <= char <= "\u9fff" for char in question) else "EPS"),
        "cash_flow": (
            "经营活动现金流" if any("\u3400" <= char <= "\u9fff" for char in question) else "operating cash flow"
        ),
        "data_center_revenue": (
            "数据中心收入" if any("\u3400" <= char <= "\u9fff" for char in question) else "Data Center revenue"
        ),
    }
    for item in result.facts:
        if not item.evidence_present or item.answer_present:
            continue
        matching = [
            ev
            for ev in items
            if _company_matches(ev, item.fact.company)
            and _period_matches(ev, item.fact.period)
            and _metric_matches_content(item.fact.metric, ev.content)
            and _fact_values(ev, item.fact.metric)
        ]
        if not matching:
            continue
        priorities = {
            "revenue": ("total net sales", "total revenues", "total revenue"),
            "net_income": ("net income $", "net income:"),
            "eps": ("diluted earnings per share",),
            "cash_flow": ("cash generated by operating activities",),
        }
        ranked = sorted(
            matching,
            key=lambda ev: max(
                (
                    index
                    for index, token in enumerate(priorities.get(item.fact.metric, ()))
                    if token in ev.content.casefold()
                ),
                default=-1,
            ),
            reverse=True,
        )
        value = next(
            (candidate for ev in ranked if (candidate := _select_fact_value(ev, item.fact)) is not None),
            None,
        )
        if value is None:
            continue
        additions.append(f"{labels.get(item.fact.metric, item.fact.metric)}: {_render_fact_value(value)}")
    if not additions:
        return answer, result, 0
    prefix = (
        "补充的证据支持事实：" if any("\u3400" <= char <= "\u9fff" for char in question) else "Evidence-backed facts: "
    )
    completed = f"{answer.rstrip()}\n\n{prefix}{'; '.join(additions)}."
    return completed, evaluate_coverage(question, completed, items), len(additions)
