"""Deterministic financial fact ledger built from retrieved evidence.

The ledger is the provenance boundary for financial numbers.  Provider output
may explain facts, but it is not allowed to invent values, metrics, periods, or
company ownership outside this structure.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, replace
from decimal import Decimal
from typing import Iterable

from agent.reasoning_models import Evidence
from core.financial_grounding import NormalizedNumber, extract_normalized_numbers
from retrieval.periods import extract_annual_periods, extract_periods

METRIC_ALIASES: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "operating_cash_flow",
        (
            "net cash provided by operating activities",
            "cash generated by operating activities",
            "operating cash flow",
            "operating activities",
            "经营活动现金流",
            "经营活动产生的现金流",
        ),
    ),
    ("cash_paid_for_taxes", ("cash paid for income taxes", "cash paid for taxes", "所得税支付现金", "支付的所得税")),
    (
        "data_center_revenue",
        (
            "data center revenue", "datacenter revenue", "data center performance", "data center growth",
            "data centre revenue", "datacentre revenue", "data centre performance", "data centre growth",
            "数据中心收入", "数据中心业务", "数据中心表现", "数据中心业绩", "数据中心增长",
        ),
    ),
    (
        "iphone_revenue",
        (
            "iphone®", "iphone net sales", "iphone revenue",
            "iphone 销售额", "iphone收入", "iphone 收入", "iphone销售额",
        ),
    ),
    (
        "products_revenue",
        ("products net sales", "products revenue", "产品净销售额", "产品收入"),
    ),
    (
        "mac_revenue",
        ("mac®", "mac net sales", "mac revenue", "Mac销售额", "Mac收入"),
    ),
    (
        "ipad_revenue",
        ("ipad®", "ipad net sales", "ipad revenue", "iPad销售额", "iPad收入"),
    ),
    (
        "wearables_revenue",
        (
            "wearables, home and accessories",
            "wearables net sales",
            "wearables revenue",
            "可穿戴设备、家居和配件",
        ),
    ),
    (
        "edge_computing_revenue",
        ("edge computing revenue", "edge revenue", "边缘计算收入", "边缘计算营收", "边缘计算业务"),
    ),
    (
        "automotive_revenue",
        (
            "total automotive revenues",
            "automotive revenue",
            "automotive business",
            "automotive segment",
            "汽车业务收入",
            "汽车业务",
            "汽车业务分部",
        ),
    ),
    (
        "services_revenue",
        (
            "services net sales",
            "services revenue",
            "services and other revenue",
            "services business",
            "service business",
            "services segment",
            "service segment",
            "service-related business",
            "service-related revenue",
            "服务收入",
            "服务业务",
            "服务相关业务",
            "服务类业务",
            "服务分部",
        ),
    ),
    (
        "energy_revenue",
        (
            "energy generation and storage revenue",
            "energy generation and storage",
            "energy revenue",
            "能源发电与储能收入",
            "能源发电和储能收入",
            "能源收入",
        ),
    ),
    ("free_cash_flow", ("free cash flow", "fcf", "自由现金流")),
    ("main_business_revenue", ("main business revenue", "core business revenue", "主营业务收入")),
    ("net_income", ("net income", "net profit", "net earnings", "净利润")),
    ("operating_income", ("income from operations", "operating income", "营业利润")),
    ("gross_profit", ("gross profit", "毛利额", "毛利润")),
    (
        "automotive_gross_margin",
        ("automotive gross margin", "汽车业务毛利率"),
    ),
    (
        "products_gross_margin",
        ("products gross margin", "metric: products", "产品毛利率"),
    ),
    (
        "services_gross_margin",
        ("services gross margin", "metric: services", "服务毛利率"),
    ),
    ("gross_margin", ("gross margin", "毛利率", "毛利")),
    ("operating_margin", ("operating margin", "operating profit margin", "营业利润率")),
    (
        "eps",
        (
            "eps",
            "eps attributable to common stockholders, diluted",
            "diluted earnings per share",
            "earnings per diluted share",
            "diluted net income per share",
            "earnings per share",
            "diluted eps",
            "每股收益",
        ),
    ),
    (
        "revenue",
        (
            "total revenues", "total revenue", "net sales", "revenue", "revenues",
            "净销售额", "总营收", "总收入", "营收", "收入",
        ),
    ),
)

_COMPANY_ALIASES = {
    "nvidia": {"nvidia", "英伟达", "英伟达公司", "nvda"},
    "apple": {"apple", "苹果", "苹果公司"},
    "tesla": {"tesla", "特斯拉"},
    "microsoft": {"microsoft", "微软"},
    "moutai": {
        "moutai", "kweichow moutai", "贵州茅台", "贵州茅台酒股份有限公司", "茅台", "600519",
    },
}


@dataclass(frozen=True)
class FinancialFact:
    fact_id: str
    company: str
    metric_id: str
    metric_label: str
    value: Decimal
    normalized_value: Decimal
    unit: str
    currency: str | None
    fiscal_year: str | None
    fiscal_quarter: str | None
    period_start: str | None
    period_end: str | None
    period_type: str
    document_reporting_period: str | None
    fact_period: str | None
    table_row_period: str | None
    table_column_period: str | None
    document: str
    page: int | None
    section: str | None
    chunk_id: str
    evidence_text: str
    confidence: float
    derivation: str = "direct"
    growth_basis: str | None = None
    display_unit: str | None = None
    # Stable ingestion identity (for example ``tesla_q2_2025``).  This is
    # deliberately kept separate from the filing/reporting period: the latter
    # remains content-derived, while the identity can provide a comparison
    # anchor only after the printed evidence proves that period exists.
    document_id: str | None = None
    dimension: str | None = None
    category: str | None = None
    # Structured statement-fact dimensions are optional so the established
    # narrative extraction path remains backwards compatible.
    company_id: str | None = None
    company_name: str | None = None
    accounting_standard: str = "UNKNOWN"
    original_label: str | None = None
    normalized_label: str | None = None
    statement_type: str | None = None
    scope: str | None = None
    raw_value: str | None = None
    source_unit: str | None = None
    mapping_status: str | None = None
    mapping_rule: str | None = None
    row_verification_status: str | None = None
    source_kind: str | None = None
    created_from: str | None = None
    table_id: str | None = None
    row_id: str | None = None
    source_locator: str | None = None
    source_text: str | None = None
    statement_period: str | None = None
    structured_identity: tuple[str, ...] | None = None

    @property
    def provenance(self) -> dict[str, object]:
        return {
            "fact_id": self.fact_id,
            "company": self.company,
            "metric_id": self.metric_id,
            "period": self.fact_period,
            "document_reporting_period": self.document_reporting_period,
            "table_row_period": self.table_row_period,
            "table_column_period": self.table_column_period,
            "period_type": self.period_type,
            "growth_basis": self.growth_basis,
            "period_start": self.period_start,
            "period_end": self.period_end,
            "document": self.document,
            "document_id": self.document_id,
            "page": self.page,
            "section": self.section,
            "chunk_id": self.chunk_id,
            "dimension": self.dimension,
            "category": self.category,
            "company_id": self.company_id,
            "company_name": self.company_name,
            "accounting_standard": self.accounting_standard,
            "original_label": self.original_label,
            "normalized_label": self.normalized_label,
            "statement_type": self.statement_type,
            "scope": self.scope,
            "raw_value": self.raw_value,
            "source_unit": self.source_unit,
            "mapping_status": self.mapping_status,
            "mapping_rule": self.mapping_rule,
            "row_verification_status": self.row_verification_status,
            "source_kind": self.source_kind,
            "created_from": self.created_from,
            "table_id": self.table_id,
            "row_id": self.row_id,
            "source_locator": self.source_locator,
            "source_text": self.source_text,
            "statement_period": self.statement_period,
        }


def canonical_company(value: str) -> str:
    lowered = (value or "").casefold()
    for company, aliases in _COMPANY_ALIASES.items():
        if lowered in aliases or any(alias in lowered for alias in aliases):
            return company
    return lowered.strip()


def metric_aliases(metric_id: str) -> tuple[str, ...]:
    for metric, aliases in METRIC_ALIASES:
        if metric == metric_id:
            return aliases
    return ()


def canonical_metric_id(text: str) -> str | None:
    lowered = (text or "").casefold()
    for metric, aliases in METRIC_ALIASES:
        if any(alias.casefold() in lowered for alias in aliases):
            return metric
    return None


def _period_from_metadata(metadata: dict, content: str) -> tuple[str | None, str | None, str | None, str | None]:
    document_period = str(metadata.get("quarter") or metadata.get("document_reporting_period") or "") or None
    row_period = metadata.get("evidence_row_period") or metadata.get("row_period")
    column_period = metadata.get("table_column_period") or metadata.get("column_period")
    fact_period = metadata.get("fact_period") or column_period or row_period
    table_context = str(metadata.get("table_context", "") or "")
    periods = extract_periods(content)
    if not periods and table_context:
        periods = _table_periods_from_context(table_context, document_period)
    if fact_period is None and len(periods) == 1:
        fact_period = periods[0]
    if fact_period is None and not periods and not table_context and document_period:
        normalized_document_period = document_period.strip().casefold().replace("-", "_")
        if normalized_document_period not in {"unknown", "undated", "none", "null", "n_a", "na"}:
            # A narrative metric row without an inline period belongs to the
            # source report's content-verified reporting period. Do not apply
            # this fallback to comparative tables, where the column must be
            # resolved from its printed header.
            fact_period = document_period
    if document_period is None and periods:
        document_period = periods[0]
    return (
        document_period,
        str(fact_period) if fact_period else None,
        str(row_period) if row_period else None,
        str(column_period) if column_period else None,
    )


def _table_periods_from_context(
    table_context: str,
    document_period: str | None,
) -> tuple[str, ...]:
    """Infer comparative column keys from a carried table header.

    Explicit quarter columns take precedence over the filing label. Calendar
    date columns retain the reporting-quarter key only as an anchor; duration
    is tracked independently so six-month totals are not quarterly facts.
    """

    explicit = extract_periods(table_context)
    if explicit:
        return explicit
    annual_periods = extract_annual_periods(table_context)
    if annual_periods and not re.search(
        r"\b(?:three|six|nine)\s+months?\s+(?:ended|ending)\b",
        table_context,
        re.IGNORECASE,
    ):
        # Year-only columns in a multi-year financial summary are annual
        # periods, not quarters inferred from the PDF's Q4/FY cover label.
        return annual_periods
    if not document_period:
        return ()
    match = re.match(r"(Q[1-4])(?:_FY)?_?(20\d{2})", document_period, re.IGNORECASE)
    if not match:
        return ()
    quarter = match.group(1).upper()
    fiscal = "_FY" if "FY" in document_period.upper() else "_"
    years = re.findall(r"\b(20\d{2})\b", table_context)
    ordered_years = list(dict.fromkeys(years))
    if not ordered_years:
        return ()
    if fiscal == "_FY":
        reporting_year = int(match.group(2))
        return tuple(
            f"{quarter}_FY{reporting_year - index}"
            for index, _ in enumerate(ordered_years)
        )
    return tuple(f"{quarter}{fiscal}{year}" for year in ordered_years)


def _period_for_value(periods: tuple[str, ...], index: int, fallback: str | None) -> str | None:
    if len(periods) > index:
        return periods[index]
    return fallback


def _inline_annual_period_after_amount(
    content: str, metric_end: int, *, content_type: str, table_context: str
) -> str | None:
    """Bind a narrative amount to an immediately stated annual period.

    Summary prose can mention a full-year amount and a quarter amount in the
    same filing-level chunk (for example, ``operating cash flow of $14.7B in
    2025; $3.8B in Q4``).  The document's quarter is not authority for the
    first amount when its own clause explicitly says ``in 2025``.  Structured
    rows already carry column periods and do not use this fallback.
    """
    if table_context or content_type.casefold() not in {"narrative", "mixed"}:
        return None
    remainder = content[metric_end : metric_end + 180]
    amount = re.search(
        r"(?<![A-Za-z0-9])(?:\$\s*|US\$\s*|USD\s*)?\(?-?\d[\d,]*(?:\.\s*\d+)?\)?\s*"
        r"(?:thousand|million|billion|[KMBT])\b",
        remainder,
        re.IGNORECASE,
    )
    if not amount:
        return None
    period = re.match(r"\s*(?:in|for|during)\s+(?:FY\s*)?(?P<year>20\d{2})\b", remainder[amount.end() :], re.I)
    if not period:
        return None
    return f"FY{period.group('year')}"


def _unit_context_for_metric(content: str, start: int, table_context: str) -> str:
    """Return the nearest reliable table scale declaration for a metric row.

    PDF layout extraction can place the table heading well after introductory
    prose in a chunk, so inspecting only the first few characters loses notes
    such as ``($ in millions)``. Prefer explicit table metadata; otherwise use
    the closest preceding declaration within a bounded table-sized window.
    """

    scale_pattern = re.compile(
        r"(?:\$\s*)?in\s+(?:thousands?|millions?|billions?)\b",
        re.IGNORECASE,
    )
    chinese_scale_pattern = re.compile(r"(?:单位\s*[:：]?\s*)?(?:千元|万元|亿元|元)(?![\u4e00-\u9fff])")
    if scale_pattern.search(table_context) or chinese_scale_pattern.search(table_context):
        return table_context.casefold()

    prefix = content[max(0, start - 1800) : start]
    declarations = list(scale_pattern.finditer(prefix))
    chinese_declarations = list(chinese_scale_pattern.finditer(prefix))
    if declarations or chinese_declarations:
        latest = max(
            [declaration.start() for declaration in (*declarations, *chinese_declarations)],
            default=0,
        )
        return prefix[latest:].casefold()

    # Preserve legacy chunks where the declaration appears at the start but
    # no nearby row-local metadata was carried through retrieval.
    return f"{table_context}\n{content[:240]}".casefold()


def _declared_table_scale(unit_context: str) -> Decimal | None:
    """Read an explicit English or Chinese monetary scale from table metadata."""
    english = re.search(
        r"(?:\$\s*)?in\s+(?P<scale>billions?|millions?|thousands?)\b",
        unit_context,
        re.IGNORECASE,
    )
    if english:
        scale = english.group("scale").casefold()
        if scale.startswith("billion"):
            return Decimal("1000000000")
        if scale.startswith("million"):
            return Decimal("1000000")
        return Decimal("1000")

    chinese = re.search(r"(?:单位\s*[:：]?\s*)?(?P<scale>千元|万元|亿元|元)(?![\u4e00-\u9fff])", unit_context)
    if not chinese:
        return None
    return {
        "千元": Decimal("1000"),
        "万元": Decimal("10000"),
        "亿元": Decimal("100000000"),
        "元": Decimal("1"),
    }[chinese.group("scale")]


def _declared_table_currency(unit_context: str) -> str | None:
    """Inherit only an explicit currency declaration; never guess USD for a bare value."""
    if re.search(r"\b(?:CNY|RMB)\b|人民币", unit_context, re.IGNORECASE):
        return "cny"
    if re.search(r"\bUSD\b|US\$|美元", unit_context, re.IGNORECASE):
        return "usd"
    if re.search(r"\bEUR\b|欧元", unit_context, re.IGNORECASE):
        return "eur"
    return None


def _is_chinese_revenue_submetric(
    content: str, start: int, alias: str, *, content_type: str
) -> bool:
    """Require a company-wide Chinese label before using a broad revenue alias."""
    if not re.search(r"[\u3400-\u9fff]", alias):
        return False
    line_start = content.rfind("\n", 0, start) + 1
    line_end = content.find("\n", start)
    if line_end < 0:
        line_end = len(content)
    if content_type.casefold() == "table":
        row_label = content[line_start:line_end].split("|", 1)[0]
        row_label = re.split(r"(?<![A-Za-z])\d[\d,]*(?:\.\d+)?", row_label, maxsplit=1)[0]
    else:
        preceding_text = content[max(line_start, start - 60) : start]
        row_label = re.split(r"[。；，,|:：\s]", preceding_text)[-1] + alias
    label = re.sub(r"\s+", "", row_label)
    if label.endswith("营业总收入"):
        return True
    for total_label in ("营业收入", "净销售额", "总营收", "总收入", "营收"):
        if label.endswith(total_label):
            modifier = label[: -len(total_label)]
            return bool(
                re.search(
                    r"业务|分部|地区|产品|渠道|项目|板块|类别|行业|酒类贸易|"
                    r"批发代理|直销|国内|国外|境内|境外|海外|利息|营业外",
                    modifier,
                )
            )
    return label != "收入"


def _is_chinese_metric_overlap(content: str, start: int, end: int, alias: str, metric_id: str) -> bool:
    """Reject an alias embedded inside a distinct attributed or ratio metric."""
    if metric_id == "operating_income" and alias == "营业利润":
        return content[end : end + 1] == "率"
    if metric_id != "net_income" or alias != "净利润":
        return False
    preceding = content[max(0, start - 80) : start]
    clause = re.split(r"[。；，,|\n]", preceding)[-1]
    return bool(re.search(r"归属于|归母|母公司|上市公司股东", clause))


def _unit(value: NormalizedNumber) -> str:
    if value.kind == "percent":
        return "percent"
    if value.kind == "basis_points":
        return "basis_points"
    magnitude = abs(value.value)
    if magnitude >= Decimal("1000000000"):
        return "billion"
    if magnitude >= Decimal("1000000"):
        return "million"
    if magnitude >= Decimal("1000"):
        return "thousand"
    return "base"


_PAIRED_MARGIN_BASIS = re.compile(
    r"\bGAAP\s+and\s+non[-\s\u2010-\u2014]?GAAP\s+"
    r"(?P<metric>gross\s+margins?|operating\s+margins?)\s+"
    r"(?:were|was)\s+(?P<gaap>-?\d[\d,]*(?:\.\d+)?)\s*%\s+and\s+"
    r"(?P<non_gaap>-?\d[\d,]*(?:\.\d+)?)\s*%\s*,?\s*respectively\b",
    re.IGNORECASE,
)


_PAIRED_EPS_BASIS = re.compile(
    r"\bGAAP\s+and\s+non[-\s\u2010-\u2014]?GAAP\s+"
    r"(?P<metric>(?:diluted\s+)?earnings\s+per\s+(?:diluted\s+)?share)\s+"
    r"(?:were|was)\s+(?P<gaap>(?:US\$|\$)?\s*-?\d[\d,]*(?:\.\d+)?)\s+and\s+"
    r"(?P<non_gaap>(?:US\$|\$)?\s*-?\d[\d,]*(?:\.\d+)?)\s*,?\s*respectively\b",
    re.IGNORECASE,
)


_PAIRED_INCOME_BASIS = re.compile(
    r"\bGAAP\s+and\s+non[-\s\u2010-\u2014]?GAAP\s+"
    r"(?P<metric>net\s+income|operating\s+income)\s+"
    r"(?:were|was)\s+(?P<gaap>(?:US\$|\$)?\s*-?\d[\d,]*(?:\.\d+)?"
    r"\s*(?:thousand|million|billion|trillion|[KMBT])?(?:\s*(?:USD|US\$|EUR|CNY|RMB))?)\s+"
    r"and\s+(?P<non_gaap>(?:US\$|\$)?\s*-?\d[\d,]*(?:\.\d+)?"
    r"\s*(?:thousand|million|billion|trillion|[KMBT])?(?:\s*(?:USD|US\$|EUR|CNY|RMB))?)\s*"
    r",?\s*respectively\b",
    re.IGNORECASE,
)


def _paired_margin_match(
    content: str, metric_match: re.Match[str], metric_id: str
) -> re.Match[str] | None:
    for pair_match in _PAIRED_MARGIN_BASIS.finditer(content):
        paired_metric = (
            "gross_margin"
            if pair_match.group("metric").casefold().startswith("gross")
            else "operating_margin"
        )
        if paired_metric == metric_id and pair_match.start() <= metric_match.start() < pair_match.end():
            return pair_match
    return None


def _paired_eps_match(
    content: str, metric_match: re.Match[str], metric_id: str
) -> re.Match[str] | None:
    if metric_id != "eps":
        return None
    for pair_match in _PAIRED_EPS_BASIS.finditer(content):
        if pair_match.start() <= metric_match.start() < pair_match.end():
            return pair_match
    return None


def _paired_income_match(
    content: str, metric_match: re.Match[str], metric_id: str
) -> re.Match[str] | None:
    if metric_id not in {"net_income", "operating_income"}:
        return None
    for pair_match in _PAIRED_INCOME_BASIS.finditer(content):
        paired_metric = "net_income" if pair_match.group("metric").casefold() == "net income" else "operating_income"
        if paired_metric == metric_id and pair_match.start() <= metric_match.start() < pair_match.end():
            return pair_match
    return None


def _qualify_paired_margin_basis(
    content: str,
    match: re.Match[str],
    metric_id: str,
    value: NormalizedNumber,
    evidence_text: str,
) -> str:
    """Retain basis identity when a filing states GAAP and non-GAAP margins together."""

    if metric_id not in {"gross_margin", "operating_margin"} or value.kind != "percent":
        return evidence_text
    pair_match = _paired_margin_match(content, match, metric_id)
    if pair_match:
        for basis in ("gaap", "non_gaap"):
            paired_value = Decimal(pair_match.group(basis).replace(",", ""))
            if paired_value == value.value:
                label = "GAAP" if basis == "gaap" else "Non-GAAP"
                metric = re.sub(r"\s+", " ", pair_match.group("metric")).rstrip("s")
                return f"{label} {metric}: {evidence_text}"
    if re.search(r"\bnon[-\s\u2010-\u2014]?gaap\b", evidence_text, re.IGNORECASE):
        return evidence_text
    line_start = max(content.rfind("\n", 0, match.start()), content.rfind(".", 0, match.start())) + 1
    prefix = content[max(line_start, match.start() - 90) : match.start()]
    qualifiers = list(re.finditer(r"\bnon[-\s\u2010-\u2014]?gaap\b|\bgaap\b", prefix, re.IGNORECASE))
    if qualifiers:
        qualifier = qualifiers[-1].group(0)
        basis = "Non-GAAP" if qualifier.casefold() != "gaap" else "GAAP"
        metric = "gross margin" if metric_id == "gross_margin" else "operating margin"
        return f"{basis} {metric}: {evidence_text}"

    # Flattened filing tables often put the accounting basis in the section
    # header rather than on the metric row itself, for example:
    # ``GAAP (...) ... Gross margin 74.9%`` followed by
    # ``Non-GAAP (...) ... Gross margin 75.0%``.  The row window intentionally
    # stops at the next metric label, so inspect the nearby preceding table
    # header before treating both values as one unqualified metric.  Use the
    # nearest header: this preserves the distinction when GAAP and non-GAAP
    # tables share a chunk and does not rely on a question or document name.
    header_prefix = content[max(0, match.start() - 420) : match.start()]
    headers = list(
        re.finditer(
            r"\b(?P<basis>non[-\s\u2010-\u2014]?gaap|gaap)\b"
            r"(?=\s*(?:\([^\n)]*\))?\s*(?:q\d|fy\d{2,4}|\$|\n|$))",
            header_prefix,
            re.IGNORECASE,
        )
    )
    if headers:
        qualifier = headers[-1].group("basis")
        basis = "Non-GAAP" if qualifier.casefold() != "gaap" else "GAAP"
        metric = "gross margin" if metric_id == "gross_margin" else "operating margin"
        return f"{basis} {metric}: {evidence_text}"
    return evidence_text


def _qualify_accounting_basis(
    content: str,
    match: re.Match[str],
    metric_id: str,
    value: NormalizedNumber,
    evidence_text: str,
) -> str:
    """Keep an explicit GAAP/non-GAAP label attached to one parsed value.

    ``_metric_window`` deliberately starts at the metric alias so that a
    nearby heading cannot leak into an unrelated fact.  In prose this also
    removes a qualifier that is part of the same clause, e.g. ``GAAP net
    income was $840 million``.  Without the qualifier, preferred-fact
    selection can mistake a pair of GAAP/non-GAAP values for duplicate facts
    and choose by magnitude.  Restore only the nearest qualifier in the same
    sentence/line; do not infer a basis from document names or question text.
    """

    evidence_text = _qualify_paired_margin_basis(
        content, match, metric_id, value, evidence_text
    )
    if metric_id not in {"net_income", "operating_income", "eps"}:
        return evidence_text
    if value.kind not in {"amount", "per_share"}:
        return evidence_text
    pair_match = _paired_income_match(content, match, metric_id) or _paired_eps_match(
        content, match, metric_id
    )
    if pair_match:
        paired_values = [
            item.value
            for item in extract_normalized_numbers(pair_match.group(0))
            if item.kind == "amount"
        ]
        for basis, paired_value in zip(("gaap", "non_gaap"), paired_values, strict=False):
            if paired_value == value.value:
                label = "GAAP" if basis == "gaap" else "Non-GAAP"
                metric = (
                    "earnings per share"
                    if metric_id == "eps"
                    else re.sub(r"\s+", " ", pair_match.group("metric")).casefold()
                )
                return f"{label} {metric}: {evidence_text}"

    if re.match(r"\s*(?:non[-\s\u2010-\u2014]?gaap|gaap)\b", evidence_text, re.I):
        return evidence_text

    line_start = max(content.rfind("\n", 0, match.start()), content.rfind(".", 0, match.start())) + 1
    prefix = content[line_start : match.start()]
    qualifiers = list(
        re.finditer(r"\bnon[-\s\u2010-\u2014]?gaap\b|\bgaap\b", prefix, re.I)
    )
    if not qualifiers:
        return evidence_text
    qualifier = qualifiers[-1].group(0)
    basis = "Non-GAAP" if qualifier.casefold() != "gaap" else "GAAP"
    metric = {
        "net_income": "net income",
        "operating_income": "operating income",
        "eps": "earnings per share",
    }[metric_id]
    return f"{basis} {metric}: {evidence_text}"


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.casefold()).strip("_")


_GUIDANCE_CUE = re.compile(
    r"\b(?:guidance|outlook|forecast|expected|projected|anticipates?|"
    r"estimates?|targets?)\b|指引|展望|预计|预期|预测",
    re.IGNORECASE,
)


def _guidance_period_for_window(
    content: str,
    start: int,
    window: str,
) -> tuple[str | None, bool]:
    """Bind guidance values to a nearby explicit period, never a table header.

    A single PDF chunk often contains an actuals table followed by a guidance
    paragraph.  ``periods`` for the whole chunk therefore describes the table
    columns, not necessarily the value in the prose paragraph.  If the value
    is in a guidance clause, prefer a period written in that clause; when none
    is written, return an undated fact so downstream policy can fail closed.
    """

    before = content[max(0, start - 700) : start]
    cue_matches = list(_GUIDANCE_CUE.finditer(before))
    if not cue_matches:
        cue_matches = list(_GUIDANCE_CUE.finditer(window))
        if not cue_matches:
            return None, False
        scope = window[cue_matches[-1].start() :]
    else:
        cue = cue_matches[-1]
        # A cue from an earlier, unrelated section must not contaminate a new
        # metric row after a paragraph/table boundary.
        before_start = max(0, start - 700)
        scope_start = before_start + cue.start()
        scope = content[scope_start : min(len(content), start + 320)]

    periods = extract_periods(scope)
    if periods:
        return periods[0], True
    return None, True


def _metric_window(
    content: str, match: re.Match[str], metric_id: str, *, include_growth_context: bool = False
) -> str:
    """Return only the matched row or prose clause, never the following row.

    PDF blocks may put a row label and its numeric cells on separate lines.
    A following numeric-only line belongs to the row; another text label does
    not. On flattened tables the first numeric run ends at the next label.
    """

    start = match.start()
    line_start = content.rfind("\n", 0, start) + 1
    prefix = content[line_start:start].strip().casefold()
    if metric_id == "gross_margin" and re.search(r"\bautomotive\s*$", prefix, re.IGNORECASE):
        return ""
    structured_line = content[line_start : content.find("\n", start) if "\n" in content[start:] else len(content)]
    structured_metric = re.search(r"\bmetric\s*:\s*[^|]+", structured_line, re.IGNORECASE)
    if structured_metric and start >= line_start + structured_metric.start():
        if re.search(r":\s*%\s*(?:\$|US\$|USD|CNY|RMB|\d)", structured_line, re.IGNORECASE):
            # A percentage token before a monetary cell means extraction lost
            # a column boundary. Flattening the row shifts later amounts.
            return ""
        row_label = structured_metric.group(0).split(":", 1)[-1].strip().casefold()
        if metric_id == "revenue" and re.search(
            r"\b(?:cost\s+of|automotive|services?(?:\s+and\s+other)?|regulatory\s+credit|"
            r"data\s+cent(?:er|re)|edge(?:\s+computing)?|deferred|disaggregated|"
            r"energy\s+generation\s+and\s+storage|portion\s+of|proportion\s+of|"
            r"products?|iphone|ipad|mac)\b",
            row_label,
        ):
            return ""
        if metric_id == "automotive_revenue" and re.match(r"automotive\s+sales\b", row_label):
            return ""
        if metric_id == "eps" and re.search(
            r"\b(?:net\s+income\s+used\s+in\s+computing|shares\s+used\s+in\s+eps)\b",
            row_label,
        ):
            return ""
        # Structured table rows carry column labels and cell values in the
        # same line (``2025: 94,827``).  Do not send those labels through the
        # generic prose window: the year can otherwise be mistaken for the
        # first financial value and shift every subsequent value by a column.
        fields = structured_line[structured_metric.end() :].split("|")
        cell_values = [
            value.strip()
            for field in fields
            if (separator := field.find(":")) >= 0
            and (value := field[separator + 1 :].strip())
        ]
        if cell_values:
            # Retain the complete structured label for downstream grounding
            # and preferred-fact selection (e.g. GAAP vs non-GAAP net income).
            return structured_metric.group(0).strip() + " " + " ".join(cell_values)
    if metric_id == "eps":
        paired_eps = _paired_eps_match(content, match, metric_id)
        if paired_eps:
            return paired_eps.group(0)
    if metric_id == "eps" and re.search(
        r"\bnet\s+income\s+used\s+in\s+computing\b",
        content[max(line_start, start - 120) : start],
        re.IGNORECASE,
    ):
        # Tesla reconciliation tables contain the numerator used to compute
        # diluted EPS. It is net income (in millions), not a per-share value.
        return ""
    if metric_id == "net_income" and re.search(
        r"(?:\bin|\bto|included(?:\s+in)?|adjust(?:ment|ed|ing).*|reconcil.*)\s*$", prefix
    ):
        return ""
    if metric_id == "revenue" and re.search(
        r"(?:cost\s+of|automotive|services(?:\s+and\s+other)?|regulatory\s+credit|data\s+center|edge(?:\s+computing)?|"
        r"deferred|disaggregated|energy\s+generation\s+and\s+storage|主营业务|"
        r"portion\s+of(?:\s+total)?|proportion\s+of|product[s]?|iphone|ipad|mac)\s*$",
        prefix,
    ):
        return ""
    if metric_id == "revenue" and re.match(
        r"\s+(?:was|were)\s+impacted\s+by\b",
        content[match.end() : match.end() + 100],
        re.IGNORECASE,
    ):
        # A revenue-driver explanation can mention a dollar-denominated FX
        # impact much later in a bullet list. That operand is not the revenue
        # amount for the report period.
        return ""
    if metric_id == "revenue" and re.match(
        r"\s+(?:and|or)\s+", content[match.end() : match.end() + 20], re.IGNORECASE
    ):
        # A later duration or purchase figure does not belong to the first
        # noun in a paired narrative phrase ("revenue and inventory ...").
        return ""

    remainder = content[match.end() : match.end() + 600]
    first_line, _, remaining = remainder.partition("\n")
    # A colon followed by another labelled row introduces components, not a
    # value for the parent metric (e.g. depreciation under OCF adjustments).
    if not re.search(r"\d", first_line):
        following = remaining.lstrip("\r\n ")
        if re.match(r"(?:\$\s*)?\(?-?\d", following):
            first_line += " " + following.split("\n", 1)[0]
        elif remaining:
            return ""

    # Truncate at another financial metric even in a one-line PDF table or
    # compound sentence. Keep same-metric plurals inside the matched label.
    boundaries = [len(first_line)]
    for other_metric, aliases in METRIC_ALIASES:
        for alias in aliases:
            other = re.search(re.escape(alias), first_line, re.IGNORECASE)
            if other and (other.start() > 0 or other_metric != metric_id):
                boundaries.append(other.start())
    sentence = re.search(r"[;。]|\.(?=\s+[A-Z])", first_line)
    if sentence:
        boundaries.append(sentence.start())
    first_line = first_line[: min(boundaries)]

    # A table's numeric run contains numbers, units and punctuation only.
    # Stopping when a new label starts also protects against rows not covered
    # by METRIC_ALIASES, such as depreciation or gross profit.
    number = re.search(r"(?:\$\s*)?\(?-?\d[\d,]*(?:\.\s*\d+)?", first_line)
    if number:
        tail = first_line[number.start() :]
        tokens = re.match(
            r"(?:(?:USD|US\$|EUR|CNY|RMB|\$)?\s*\(?-?\d[\d,]*(?:\.\s*\d+)?\)?"
            r"\s*(?:thousand|million|billion|trillion|亿|万|[KMBT])?"
            r"\s*(?:USD|US\$|EUR|CNY|RMB|美元|人民币|dollars?)?"
            r"\s*(?:%|percent|basis points|bps|bp)?[\s,|]*)+",
            tail,
            re.IGNORECASE,
        )
        # Narrative clauses may place a quarter/year before the actual
        # amount; leave those to the normalizer, which drops period labels.
        if tokens and not re.search(r"\b(?:Q[1-4]|FY\d{4})\b", first_line[:number.end()], re.I):
            numeric_end = number.start() + tokens.end()
            growth_context = re.match(
                r"[\s,]*(?:up|down|increased?|decreased?|grew|growth|yoy|qoq|year[- ]over[- ]year|"
                r"quarter[- ]over[- ]quarter|同比|环比)\b",
                first_line[numeric_end:],
                re.IGNORECASE,
            )
            if not (include_growth_context and growth_context):
                first_line = first_line[:numeric_end]
    return content[start : match.end()] + first_line


_GROWTH_RATE_TOKEN = re.compile(
    r"(?P<number>\(?-?\d[\d,]*(?:\.\s*\d+)?\)?)\s*(?:%|percent\b)",
    re.IGNORECASE,
)
_GROWTH_BASIS_PATTERNS = {
    "yoy": re.compile(
        r"\b(?:y\s*/\s*y|yoy|year[- ]over[- ]year|from\s+(?:a|the same period a)\s+year\s+ago|"
        r"from\s+a\s+year\s+earlier|from\s+last\s+year)\b|同比|较上年同期",
        re.IGNORECASE,
    ),
    "qoq": re.compile(
        r"\b(?:q\s*/\s*q|qoq|quarter[- ]over[- ]quarter|from\s+(?:the\s+)?previous\s+quarter|"
        r"sequential(?:ly)?)\b|环比|较上季度",
        re.IGNORECASE,
    ),
}


def _reported_growth_rates(window: str) -> tuple[tuple[str, Decimal], ...]:
    """Extract only explicitly reported YoY/QoQ percentages near a metric value.

    The rate stays separate from the base financial amount and is bound to the
    comparison phrase closest to it. Percentage-point changes are not growth
    rates. Ambiguous rates without an explicit comparison basis are omitted.
    """

    rates: list[tuple[str, Decimal]] = []
    for match in _GROWTH_RATE_TOKEN.finditer(window):
        left = max(0, match.start() - 64)
        right = min(len(window), match.end() + 64)
        context = window[left:right]
        nearby_anchors: list[tuple[int, str]] = []
        for basis, pattern in _GROWTH_BASIS_PATTERNS.items():
            for anchor in pattern.finditer(context):
                absolute_start = left + anchor.start()
                absolute_end = left + anchor.end()
                distance = max(0, max(match.start() - absolute_end, absolute_start - match.end()))
                if distance <= 48:
                    nearby_anchors.append((distance, basis))
        if not nearby_anchors:
            continue
        nearby_anchors.sort()
        if len(nearby_anchors) > 1 and nearby_anchors[0][0] == nearby_anchors[1][0]:
            continue
        if re.search(r"(?:percentage\s+points?|\bpts?\b|百分点)", context, re.IGNORECASE):
            continue
        raw_number = match.group("number").replace(",", "").replace(" ", "")
        number = Decimal(raw_number.strip("()"))
        if raw_number.startswith("(") or raw_number.startswith("-"):
            number = -abs(number)
        verb_context = window[max(0, match.start() - 28):match.start()]
        if re.search(
            r"\b(?:down|decreased?|declined?|fell|lower(?:ed)?)\b|下降|下滑|减少|降低|回落",
            verb_context,
            re.I,
        ):
            number = -abs(number)
        elif re.search(r"\b(?:up|increased?|grew|rose|higher)\b|上升|增长|增加", verb_context, re.I):
            number = abs(number)
        basis = nearby_anchors[0][1]
        value = (basis, number)
        if value not in rates:
            rates.append(value)
    return tuple(rates)


def _metric_clause(content: str, match: re.Match[str]) -> str:
    """Return the sentence containing a metric when a row window is unusable."""

    separator = re.compile(r"[!?;。！？；]\s*|\.(?=\s+[A-Z\u3400-\u9fff])|\n+")
    start = 0
    end = len(content)
    for boundary in separator.finditer(content):
        if boundary.end() <= match.start():
            start = boundary.end()
        elif boundary.start() >= match.end():
            end = boundary.start()
            break
    return content[start:end].strip()


def _growth_fact(base_fact: FinancialFact, basis: str, value: Decimal, evidence_text: str) -> FinancialFact:
    return replace(
        base_fact,
        fact_id=(
            f"{_slug(base_fact.company or 'unknown')}_{base_fact.metric_id}_"
            f"{_slug(base_fact.fact_period or 'undated')}_{basis}_"
            f"{_slug(format(value.normalize(), 'f'))}_{_slug(base_fact.chunk_id[-12:] or base_fact.document)}"
        ),
        metric_label=f"{base_fact.metric_label} {basis.upper()} growth",
        value=value,
        normalized_value=value,
        unit="percent",
        currency=None,
        # The base fact may be rendered in the statement's display scale
        # (for example ``million``). Growth values are percentages and must
        # never inherit that amount-only display hint.
        display_unit=None,
        evidence_text=evidence_text[:420],
        derivation="reported_growth",
        growth_basis=basis,
    )


def _structured_growth_rates(
    content: str, match: re.Match[str]
) -> tuple[tuple[str, Decimal, str], ...] | None:
    """Bind a labelled growth cell to the last explicit period column before it.

    Structured row text preserves its original period and comparison columns,
    for example ``Q4-2025: 24,901 | YoY: -3%``. The rate describes Q4-2025; it
    must not be copied onto every historical amount in the same row.

    ``None`` means the row is not explicitly structured with comparison cells.
    An empty tuple means it is such a row, but the comparison cell could not be
    safely resolved; callers must then fail closed instead of using proximity.
    """

    line_start = content.rfind("\n", 0, match.start()) + 1
    line_end = content.find("\n", match.end())
    if line_end < 0:
        line_end = len(content)
    line = content[line_start:line_end]
    metric_label = re.search(r"\bmetric\s*:", line, re.IGNORECASE)
    if metric_label is None or "|" not in line:
        return None

    fields = line[metric_label.start() :].split("|")
    explicit_periods: list[str] = []
    rates: list[tuple[str, Decimal, str]] = []
    found_growth_column = False
    for field in fields:
        separator = field.find(":")
        if separator < 0:
            continue
        label = field[:separator].strip()
        raw_value = field[separator + 1 :].strip()
        periods = extract_periods(label) or extract_annual_periods(label)
        if periods:
            explicit_periods.extend(periods)
            continue

        normalized_label = re.sub(r"\s+", " ", label).strip().casefold()
        if re.fullmatch(r"(?:yoy|y/y|year[- ]over[- ]year)(?:\s+(?:change|growth|%)|%)?", normalized_label):
            basis = "yoy"
        elif re.fullmatch(
            r"(?:qoq|q/q|quarter[- ]over[- ]quarter)(?:\s+(?:change|growth|%)|%)?",
            normalized_label,
        ):
            basis = "qoq"
        else:
            continue

        found_growth_column = True
        values = [
            value.value
            for value in extract_normalized_numbers(raw_value)
            if value.kind == "percent"
        ]
        if explicit_periods and len(values) == 1:
            # Comparative rows are not required to list the current period
            # last. Choose the newest explicitly labelled period rather than
            # binding a rate to the last token seen. This works for both
            # quarter tables and annual FY columns.
            def period_key(value: str) -> tuple[int, int, int]:
                match = re.fullmatch(
                    r"Q(?P<quarter>[1-4])_(?P<fiscal>FY)?(?P<year>20\d{2})",
                    str(value),
                    re.IGNORECASE,
                )
                if match:
                    return (
                        int(match.group("year")),
                        int(match.group("quarter")),
                        1 if match.group("fiscal") else 0,
                    )
                annual = re.fullmatch(r"FY(?P<year>20\d{2})", str(value), re.IGNORECASE)
                if annual:
                    return (int(annual.group("year")), 0, 1)
                return (-1, -1, -1)

            latest_period = max(explicit_periods, key=period_key)
            rates.append((basis, values[0], latest_period))

    return tuple(rates) if found_growth_column else None


def _attach_growth_to_existing_fact(
    facts: list[FinancialFact],
    *,
    company: str,
    chunk_id: str,
    content: str,
    match: re.Match[str],
    metric_id: str,
    periods: tuple[str, ...],
    fallback_period: str | None,
) -> None:
    """Bind a reported growth clause to an already parsed same-row amount."""

    if metric_id != "revenue":
        return
    before = content[max(0, match.start() - 50):match.start()].casefold()
    if re.search(
        r"(?:data\s+cent(?:er|re)|datacent(?:er|re)|edge(?:\s+computing)?|"
        r"automotive|services?|数据中心|边缘计算|汽车业务|服务业务)\s*$",
        before,
        re.IGNORECASE,
    ):
        return
    structured_rates = _structured_growth_rates(content, match)
    if structured_rates is not None:
        for basis, value, fact_period in structured_rates:
            base_fact = next((
                fact for fact in reversed(facts)
                if fact.company == company
                and fact.metric_id == "revenue"
                and fact.chunk_id == chunk_id
                and fact.growth_basis is None
                and fact.fact_period
                and periods_equivalent(fact.fact_period, fact_period)
            ), None)
            if base_fact:
                facts.append(_growth_fact(base_fact, basis, value, _metric_clause(content, match)))
        return

    rates = _reported_growth_rates(_metric_clause(content, match))
    if not rates:
        return
    fact_period = _period_for_value(periods, 0, fallback_period)
    base_fact = next((
        fact for fact in reversed(facts)
        if fact.company == company
        and fact.metric_id == "revenue"
        and fact.chunk_id == chunk_id
        and fact.growth_basis is None
        and fact.fact_period
        and periods_equivalent(fact.fact_period, fact_period)
    ), None)
    if base_fact:
        facts.extend(
            _growth_fact(base_fact, basis, value, _metric_clause(content, match))
            for basis, value in rates
        )


def _preceding_section_heading(content: str, position: int) -> str:
    """Return the nearest preceding non-empty line before a metric row."""
    current_line_start = content.rfind("\n", 0, position) + 1
    preceding_lines = content[:current_line_start].splitlines()
    return next(
        (line.strip().strip("#* ").casefold() for line in reversed(preceding_lines) if line.strip()),
        "",
    )


def _structured_row_dimension(content: str, position: int) -> tuple[str | None, str | None]:
    """Return the explicit dimension/category on the structured row at position."""
    # 同一文本块可能紧邻产品、地区或销售渠道多行；只取当前数值所在行的标签，避免跨行借用类别。
    marker = "structured financial table row"
    lowered = content.casefold()
    row_start = lowered.rfind(marker, 0, position)
    if row_start < 0:
        return None, None
    row_end = lowered.find(marker, position)
    if row_end < 0:
        row_end = len(content)
    row = content[row_start:row_end]
    match = re.search(
        r"\bDimension\s*:\s*(?P<dimension>[^;|]+?)\s*;\s*"
        r"Category\s*:\s*(?P<category>[^|\n]+)",
        row,
        re.IGNORECASE,
    )
    if not match:
        return None, None
    return match.group("dimension").strip() or None, match.group("category").strip() or None


def _period_type(context: str, index: int, column_count: int, default: str) -> str:
    """Keep cumulative statement durations distinct from quarter columns."""

    lowered = context.casefold()
    compound = re.search(
        r"(three|six|nine|twelve)\s*-\s*and\s*"
        r"(three|six|nine|twelve)\s*-\s*months?",
        lowered,
    )
    if compound:
        months = [compound.group(1), compound.group(2)]
    else:
        months = re.findall(r"(three|six|nine|twelve)[ -]months?(?:\s+ended)?", lowered)
    months = list(dict.fromkeys(months))
    comparative = re.search(
        r"comparative\s+columns\s*:\s*(.*)", lowered, re.DOTALL,
    )
    if comparative:
        labelled_columns = re.findall(
            r"\b(?:ytd\s+)?q[1-4]\s*(?:fy\s*)?20\d{2}\b",
            comparative.group(1),
        )
        column_count = max(column_count, len(labelled_columns))
    if len(months) > 1 and column_count:
        # SEC income statements place all quarter columns before YTD columns.
        # ``column_count`` is the total number of comparative cells, so each
        # duration owns a contiguous group (e.g. Q2/Q1 then YTD Q2/YTD Q1).
        group_size = max(1, (column_count + len(months) - 1) // len(months))
        duration = months[min(index // group_size, len(months) - 1)]
    elif months:
        duration = months[0]
    else:
        if re.search(r"\bttm\b|trailing twelve months", lowered):
            return "trailing_twelve_months"
        return default
    return {"three": "fiscal_quarter", "six": "six_months", "nine": "nine_months", "twelve": "fiscal_year"}[duration]


def periods_equivalent(left: str | None, right: str | None) -> bool:
    if not left or not right:
        return left == right

    def normalize(value: str) -> str:
        return re.sub(r"_FY", "_", value.upper().replace("-", "_"))

    return normalize(left) == normalize(right)


def _is_table_header_metric_match(
    content: str, start: int, *, content_type: str,
) -> bool:
    """Reject metric aliases that occur only in a statement header.

    Apple 10-Q chunks carry a ``TABLE COLUMNS`` header such as
    ``net income in millions and shares in thousands`` before the actual
    rows.  Treating that header as a financial row creates a bogus negative
    value (``-2.026`` from the fiscal-year token) for every metric alias in
    the same chunk.  Only skip the match when the containing line is clearly
    header metadata and does not itself contain a labelled table row.
    """

    if content_type != "table":
        return False
    line_start = content.rfind("\n", 0, start) + 1
    line_end = content.find("\n", start)
    if line_end < 0:
        line_end = len(content)
    line = content[line_start:line_end]
    if re.search(r"\bfinancial\s+table\s+row\b|\bmetric\s*:", line, re.IGNORECASE):
        return False
    header = re.search(
        r"\btable\s+columns\b|\bcomparative\s+columns\b|"
        r"\bnet\s+income\s+in\s+millions\b|"
        r"\bshares\s+in\s+thousands\b",
        line,
        re.IGNORECASE,
    )
    if not header:
        return False
    # PDF extraction can flatten a table header and its first row onto one
    # physical line (``TABLE COLUMNS: ... Q4-2025. Total revenues ...``).
    # The metric after a sentence/column delimiter is a real row, not header
    # metadata.  Header-only aliases remain rejected.
    suffix_before_match = line[header.end() : start]
    if re.search(r"[.!?;|]\s*$|:\s*$", suffix_before_match):
        return False
    return True


class FactLedger:
    """Immutable collection of extracted facts with deterministic lookup."""

    def __init__(self, facts: Iterable[FinancialFact] = ()) -> None:
        unique: dict[tuple, FinancialFact] = {}
        fact_items = tuple(facts)
        grouped_structured: dict[tuple[str, ...], list[FinancialFact]] = {}
        for fact in fact_items:
            if fact.structured_identity is not None:
                grouped_structured.setdefault(fact.structured_identity, []).append(fact)
        self.conflicts: tuple[dict[str, object], ...] = tuple(
            {
                "identity": identity,
                "facts": tuple(fact.provenance | {"value": str(fact.normalized_value)} for fact in group),
                "status": "FACT_CONFLICT",
            }
            for identity, group in grouped_structured.items()
            if len({fact.normalized_value for fact in group}) > 1
        )
        conflicting_identities = {conflict["identity"] for conflict in self.conflicts}
        for fact in fact_items:
            if fact.structured_identity in conflicting_identities:
                continue
            key = ("structured", fact.structured_identity) if fact.structured_identity is not None else (
                fact.company,
                fact.metric_id,
                fact.fact_period,
                fact.normalized_value,
                fact.chunk_id,
                fact.growth_basis,
                fact.dimension,
                fact.category,
            )
            unique.setdefault(key, fact)
        self.facts = tuple(unique.values())
        self._by_id = {fact.fact_id: fact for fact in self.facts}

    @classmethod
    def from_financial_facts(cls, facts: Iterable[FinancialFact]) -> "FactLedger":
        """Consume already validated canonical facts without re-extracting text."""
        return cls(facts)

    @classmethod
    def from_evidence(cls, evidence: Iterable[Evidence]) -> "FactLedger":
        facts: list[FinancialFact] = []
        for item in evidence:
            metadata = dict(item.metadata or {})
            if str(metadata.get("content_type", "")).casefold() == "unverified_table":
                continue
            if "financial_table_rows_json" in metadata:
                # Structured facts are created only from typed rows through
                # the P1.5 fail-closed gate. Legacy text extraction is never
                # used as a fallback for rejected or incomplete rows.
                from core.financial_facts import (
                    EligibilityStatus,
                    FinancialDocumentContext,
                    FinancialFactFactory,
                    rows_from_json,
                )

                standard = str(metadata.get("accounting_standard", "UNKNOWN")).upper()
                standard_source = str(metadata.get("accounting_standard_source", "")) or None
                if standard != "UNKNOWN" and not standard_source:
                    standard = "UNKNOWN"
                try:
                    context = FinancialDocumentContext(
                        company_id=str(metadata.get("company_id", "")) or None,
                        company_name=str(
                            metadata.get("company_name", item.company or metadata.get("company", ""))
                        )
                        or None,
                        accounting_standard=standard,
                        accounting_standard_source=standard_source,
                        fiscal_year_start=str(metadata.get("fiscal_year_start", "")) or None,
                        fiscal_year_end=str(metadata.get("fiscal_year_end", "")) or None,
                        fiscal_calendar_source=str(metadata.get("fiscal_calendar_source", "")) or None,
                    )
                    table_rows = rows_from_json(str(metadata["financial_table_rows_json"]))
                except (TypeError, ValueError):
                    # Invalid document metadata is rejected, never reparsed as narrative.
                    continue
                factory = FinancialFactFactory()
                for row in table_rows:
                    decision = factory.gate.assess(row, context=context)
                    if decision.status != EligibilityStatus.ELIGIBLE:
                        continue
                    try:
                        fact = factory.create(
                            row, context=context, normalization=decision.normalization
                        )
                        # Evidence citations identify the indexed chunk, while the
                        # row locator identifies its position in the source PDF.
                        # Keep both: projection needs the former to cite the fact.
                        facts.append(
                            replace(fact, chunk_id=str(metadata.get("chunk_id") or fact.chunk_id))
                        )
                    except ValueError:
                        # A malformed unit/period remains ineligible; do not
                        # demote it to narrative extraction.
                        continue
                continue
            company = canonical_company(str(item.company or metadata.get("company", "")))
            content = str(item.content or "")
            table_context = str(metadata.get("table_context", "") or "")
            # Printed quarter headers outrank a potentially filename-derived
            # document label (notably Tesla historical comparison tables).
            printed_periods = extract_periods(table_context)
            table_periods = _table_periods_from_context(
                table_context or content,
                str(metadata.get("quarter") or metadata.get("document_reporting_period") or "") or None,
            )
            periods = printed_periods or table_periods or extract_periods(content)
            document_period, fallback_period, row_period, column_period = _period_from_metadata(metadata, content)
            chunk_id = str(metadata.get("chunk_id", ""))
            document_id = str(metadata.get("document_id", "")) or None
            source = str(item.source or metadata.get("source", ""))
            for metric_id, aliases in METRIC_ALIASES:
                for alias in aliases:
                    for match in re.finditer(re.escape(alias), content, re.IGNORECASE):
                        start = match.start()
                        if _is_chinese_metric_overlap(content, start, match.end(), alias, metric_id):
                            continue
                        if metric_id == "revenue" and _is_chinese_revenue_submetric(
                            content,
                            start,
                            alias,
                            content_type=str(metadata.get("content_type", "")),
                        ):
                            continue
                        if _is_table_header_metric_match(
                            content,
                            start,
                            content_type=str(metadata.get("content_type", "")).casefold(),
                        ):
                            continue
                        paired_margin = (
                            _paired_margin_match(content, match, metric_id)
                            or _paired_eps_match(content, match, metric_id)
                            or _paired_income_match(content, match, metric_id)
                        )
                        # The normal single-metric window intentionally stops
                        # at another metric label. In a filing's explicit
                        # "GAAP and non-GAAP ... were X and Y, respectively"
                        # construction, that boundary is part of the same
                        # paired fact and must retain both values.
                        window = (
                            paired_margin.group(0)
                            if paired_margin
                            else _metric_window(
                                content,
                                match,
                                metric_id,
                                include_growth_context=metric_id == "revenue",
                            )
                        )
                        if (
                            not window
                            and metric_id == "eps"
                            and str(metadata.get("content_type", "")).casefold() == "table"
                            and re.search(
                                r"\bverified statement group:\s*earnings\s+per\s+share\b",
                                content,
                                re.IGNORECASE,
                            )
                            and not re.search(r"\bshares used in computing\b", content, re.IGNORECASE)
                        ):
                            diluted_row = next(
                                (
                                    row
                                    for row in content.splitlines()
                                    if re.search(r"\bmetric\s*:\s*diluted\b", row, re.IGNORECASE)
                                ),
                                "",
                            )
                            value_cells = [
                                value_match.group(1).strip()
                                for field in diluted_row.split("|")[1:]
                                if (value_match := re.search(r":\s*(.+)$", field))
                            ]
                            if value_cells:
                                # The row parser already bound every value to
                                # its printed period column. Remove those
                                # labels before numeric normalization so FY
                                # digits cannot be mistaken for EPS values.
                                window = "Diluted " + " ".join(value_cells)
                        if not window:
                            _attach_growth_to_existing_fact(
                                facts,
                                company=company,
                                chunk_id=chunk_id,
                                content=content,
                                match=match,
                                metric_id=metric_id,
                                periods=periods,
                                fallback_period=fallback_period,
                            )
                            continue
                        if metric_id in {"products_gross_margin", "services_gross_margin"}:
                            # The structured Apple row label is simply
                            # ``Metric: Services``/``Metric: Products`` and
                            # therefore also appears in the net-sales table.
                            # Require the surrounding verified statement group
                            # to be a gross-margin table before accepting the
                            # percentage as a segment-margin fact.
                            if not re.search(
                                r"\bgross\s+margin(?:\s+percentage)?\b",
                                f"{table_context}\n{content[:900]}",
                                re.IGNORECASE,
                            ):
                                continue
                        if metric_id == "eps" and re.search(
                            r"shares\s+used\s+in\s+computing\s+earnings\s+per\s+share",
                            content[max(0, start - 90) : start + len(alias)],
                            re.IGNORECASE,
                        ):
                            # A share-count table contains the phrase
                            # "earnings per share" but its values are not EPS.
                            continue
                        values = extract_normalized_numbers(
                            window,
                            allow_year_like_amount=(
                                str(metadata.get("content_type", "")).casefold() == "table"
                                and bool(table_context)
                                # Explicit period-labelled cells such as
                                # ``Q2 FY2026: $80,208`` already give the
                                # normalizer a reliable year token.  Keeping
                                # that token as an amount would create a
                                # bogus -2.026 billion fact before the real
                                # cell.  The opt-in is only for flattened
                                # verified rows (e.g. Tesla's ``2,034 664
                                # 146`` FCF row) whose table context carries
                                # the columns separately.
                                and not re.search(
                                    r"\b(?:Q[1-4]|FY\s*20\d{2}|20\d{2})\b",
                                    window,
                                    re.IGNORECASE,
                                )
                            ),
                        )
                        values = [value for value in values if value.kind in {"amount", "percent", "basis_points"}]
                        unit_context = _unit_context_for_metric(
                            content,
                            start,
                            table_context,
                        )
                        # Legacy table chunks may be separated from their
                        # ``(In millions)`` header.  A carried table context
                        # plus comma-grouped values is still strong evidence
                        # of a statement row expressed in millions.  The
                        # same rule covers older Tesla/Apple table chunks
                        # where the row was indexed without table_context.
                        explicit_value_scale = bool(
                            re.search(
                                r"\d[\d,]*(?:\.\d+)?\s*(?:thousand|million|billion|trillion|千元|万元|亿元|元|亿|万|[KMBTkmbt])(?:\b|(?![\u4e00-\u9fff]))",
                                window,
                                re.IGNORECASE,
                            )
                        )
                        legacy_table_row = bool(
                            re.search(
                                r"(?:total\s+revenues?|total\s+net\s+sales|"
                                r"net\s+income(?:\s+attributable)?|cash\s+generated\s+by\s+operating\s+activities|"
                                r"net\s+cash\s+provided\s+by\s+operating\s+activities)",
                                window,
                                re.IGNORECASE,
                            )
                            and len(re.findall(r"\d{1,3}(?:,\d{3})+", window)) >= 2
                            and not explicit_value_scale
                        )
                        inferred_million_table = bool(
                            (
                                table_context
                                and re.search(r"\$\s*\(?\d{1,3}(?:,\d{3})+", window)
                            )
                            or (
                                table_context
                                and re.search(r"\(?\d{1,3}(?:,\d{3})+", window)
                            )
                            or legacy_table_row
                        )
                        table_scale = Decimal("1")
                        declared_scale = _declared_table_scale(unit_context)
                        if metric_id != "eps" and not explicit_value_scale:
                            # Use the table's primary scale declaration, not any
                            # later exception in its footnote.  For example,
                            # Apple's statement says "In millions, except
                            # shares ... reflected in thousands"; searching
                            # independently for "in thousands" used to win and
                            # under-scale every monetary value by 1,000x.
                            if declared_scale:
                                table_scale = declared_scale
                            elif inferred_million_table:
                                table_scale = Decimal("1000000")
                            elif re.search(
                                r"\bQ\d(?:[- ]\d{4}|\s+FY\d{4})\s*:\s*\d[\d,]*",
                                content,
                                re.IGNORECASE,
                            ):
                                # Explicit period-labelled statement cells
                                # commonly arrive without the table header;
                                # comma-grouped financial values use the
                                # filing's conventional millions scale.
                                table_scale = Decimal("1000000")
                        table_currency = _declared_table_currency(unit_context)
                        if table_currency is None and table_scale != 1 and company in {
                            "apple", "tesla", "nvidia", "microsoft"
                        }:
                            # Preserve the existing USD convention for the
                            # known US issuers; a Chinese monetary table must
                            # never inherit USD merely because it is scaled.
                            table_currency = "usd"
                        if table_scale != 1 or table_currency:
                            values = [
                                NormalizedNumber(
                                    value=value.value * table_scale if value.kind == "amount" else value.value,
                                    kind=value.kind,
                                    currency=value.currency or (table_currency if value.kind == "amount" else None),
                                    quantum=(
                                        value.quantum * table_scale
                                        if value.kind == "amount" and value.quantum is not None
                                        else value.quantum
                                    ),
                                )
                                for value in values
                            ]
                        if metric_id == "eps":
                            # EPS values are often unadorned decimals in a
                            # table whose neighboring monetary rows are in
                            # thousands or millions. Keep them as per-share
                            # amounts and do not magnitude-filter them.
                            values = [value for value in values if value.kind == "amount"]
                        elif metric_id in {
                            "gross_margin",
                            "automotive_gross_margin",
                            "products_gross_margin",
                            "services_gross_margin",
                        }:
                            # Some filings label the gross-profit dollar total
                            # "Total gross margin" and report the actual
                            # percentage in a separate row. Only preserve an
                            # amount here when the structured row is that
                            # explicitly labeled dollar total; never let it
                            # become a margin percentage.
                            gross_profit_amount_row = (
                                metric_id == "gross_margin"
                                and str(metadata.get("content_type", "")).casefold() == "table"
                                and re.search(
                                    r"\bfinancial table row\b[^\n]*\bmetric\s*:\s*(?:total\s+)?gross\s+margin\b",
                                    content,
                                    re.IGNORECASE,
                                )
                            )
                            values = [
                                value
                                for value in values
                                if value.kind in {"percent", "basis_points"}
                                or (value.kind == "amount" and gross_profit_amount_row)
                            ]
                        elif metric_id == "operating_margin":
                            values = [value for value in values if value.kind in {"percent", "basis_points"}]
                        else:
                            # Bare small integers next to a financial label in
                            # narrative prose are usually note/page identifiers,
                            # not monetary facts (for example ``net sales ...
                            # Note 10``). Statement rows carry currency/scale or
                            # statement-sized amounts.
                            values = [
                                value
                                for value in values
                                if value.kind == "amount"
                                and (value.currency is not None or abs(value.value) >= Decimal("1000"))
                            ]
                        if not values:
                            _attach_growth_to_existing_fact(
                                facts,
                                company=company,
                                chunk_id=chunk_id,
                                content=content,
                                match=match,
                                metric_id=metric_id,
                                periods=periods,
                                fallback_period=fallback_period,
                            )
                            continue
                        if (
                            len(values) >= 3
                            and len(periods) <= 1
                            and not table_context
                            and str(metadata.get("content_type", "")).casefold()
                            in {"narrative", "mixed"}
                        ):
                            # Flattened multi-year/quarter tables can land in a
                            # narrative block without their column header.
                            # The filing-level quarter is not enough to assign
                            # five unlabeled values to that quarter (e.g. a
                            # 2021–2025 series inside a Q4 filing). Fail closed
                            # rather than minting false period-grounded facts.
                            continue
                        inline_annual_period = _inline_annual_period_after_amount(
                            content,
                            match.end(),
                            content_type=str(metadata.get("content_type", "")),
                            table_context=table_context,
                        )
                        guidance_period, is_guidance = _guidance_period_for_window(
                            content,
                            start,
                            window,
                        )
                        value_limit = 2 if paired_margin else max(len(periods), 1)
                        for index, value in enumerate(values[:value_limit]):
                            period_index = 0 if paired_margin else index
                            if guidance_period:
                                # Guidance/outlook values belong to the
                                # explicit period in that clause, not to the
                                # first comparative table column in the same
                                # chunk.  An explicit metadata period remains
                                # a valid fallback for legacy isolated chunks.
                                fact_period = guidance_period
                            elif is_guidance:
                                # Do not silently borrow Q1 (or any other
                                # table period) when guidance has no explicit
                                # period.  This fact remains auditable but is
                                # ineligible for a period-specific answer.
                                fact_period = (
                                    fallback_period
                                    if fallback_period
                                    and fallback_period.casefold()
                                    not in {"unknown", "undated", "none", "null", "n_a", "na"}
                                    else None
                                )
                            else:
                                fact_period = (
                                    inline_annual_period
                                    if index == 0 and inline_annual_period
                                    else _period_for_value(periods, period_index, fallback_period)
                                )
                            is_fiscal_year = bool(
                                fact_period and re.fullmatch(r"FY20\d{2}", fact_period, re.IGNORECASE)
                            )
                            # Generic revenue aliases are not allowed to claim a
                            # specialized row that has an explicit metric label.
                            before = content[max(0, start - 35) : start].casefold()
                            preceding_heading = _preceding_section_heading(content, start)
                            segment_heading_metrics = {
                                "data center": ("data_center_revenue", "Data Center revenue"),
                                "datacenter": ("data_center_revenue", "Data Center revenue"),
                                "数据中心": ("data_center_revenue", "数据中心收入"),
                                "edge computing": ("edge_computing_revenue", "Edge Computing revenue"),
                                "edge": ("edge_computing_revenue", "Edge Computing revenue"),
                                "边缘计算": ("edge_computing_revenue", "边缘计算收入"),
                            }
                            segment_fact = segment_heading_metrics.get(preceding_heading)
                            if metric_id == "revenue" and any(
                                token in before
                                for token in ("automotive", "services", "data center", "数据中心", "汽车")
                            ) and segment_fact is None:
                                continue
                            fact_metric_id = metric_id
                            fact_metric_label = alias
                            if (
                                metric_id == "gross_margin"
                                and value.kind == "amount"
                                and str(metadata.get("content_type", "")).casefold() == "table"
                                and re.search(
                                    r"\bfinancial table row\b[^\n]*\bmetric\s*:\s*(?:total\s+)?gross\s+margin\b",
                                    content,
                                    re.IGNORECASE,
                                )
                            ):
                                fact_metric_id = "gross_profit"
                                fact_metric_label = "gross profit"
                            if metric_id == "revenue" and segment_fact is not None:
                                # Earnings releases often introduce a segment
                                # with a heading and then say only "First-quarter
                                # revenue was ...". Keep that amount in the
                                # segment ledger rather than misclassifying it
                                # as consolidated revenue.
                                fact_metric_id, fact_metric_label = segment_fact
                            value_text = str(value.value.normalize())
                            fact_id = (
                                f"{_slug(company or 'unknown')}_{fact_metric_id}_"
                                f"{_slug(fact_period or 'undated')}_{_slug(value_text)}_"
                                f"{_slug(chunk_id[-12:] or source)}"
                            )
                            evidence_text = (
                                paired_margin.group(0)
                                if paired_margin
                                else _metric_window(
                                    content, match, fact_metric_id, include_growth_context=True
                                )
                            )[:420]
                            evidence_text = _qualify_accounting_basis(
                                content, match, fact_metric_id, value, evidence_text
                            )
                            dimension, category = _structured_row_dimension(content, start)
                            # 把维度与类别存进事实本身，后续查找和数值校验才能沿用原表格口径。
                            facts.append(
                                base_fact := FinancialFact(
                                    fact_id=fact_id,
                                    company=company,
                                    metric_id=fact_metric_id,
                                    metric_label=fact_metric_label,
                                    value=value.value,
                                    normalized_value=value.value,
                                    unit="per_share" if metric_id == "eps" else _unit(value),
                                    currency=value.currency,
                                    fiscal_year=(
                                        fact_period[2:]
                                        if is_fiscal_year
                                        else (fact_period or "").split("_")[-1] or None
                                    ),
                                    fiscal_quarter=(
                                        None if is_fiscal_year else (fact_period or "").split("_")[0] or None
                                    ),
                                    period_start=None,
                                    period_end=None,
                                    period_type=_period_type(
                                        f"{table_context}\n{content[max(0, start - 30):match.end()]}",
                                        period_index,
                                        len(periods),
                                        (
                                            "fiscal_year"
                                            if is_fiscal_year
                                            else "fiscal_quarter"
                                            if fact_period
                                            else "document"
                                        ),
                                    ),
                                    document_reporting_period=document_period,
                                    fact_period=fact_period,
                                    table_row_period=row_period,
                                    table_column_period=column_period or fact_period,
                                    document=source,
                                    page=metadata.get("page"),
                                    section=metadata.get("section"),
                                    chunk_id=chunk_id,
                                    evidence_text=evidence_text,
                                    confidence=float(item.confidence or metadata.get("similarity", 0.0) or 0.0),
                                    display_unit=(
                                        "million"
                                        if (
                                            (
                                                str(metadata.get("content_type", "")).casefold() == "table"
                                                or re.search(r"\bfinancial\s+table\s+row\b", content, re.IGNORECASE)
                                            )
                                            and re.search(
                                                r"\bQ\d(?:[- ]\d{4}|\s+FY\d{4})\s*:\s*\d[\d,]*",
                                                content,
                                                re.IGNORECASE,
                                            )
                                            and fact_metric_id != "eps"
                                            and value.kind == "amount"
                                        )
                                        else None
                                    ),
                                    document_id=document_id,
                                    dimension=dimension,
                                    category=category,
                                )
                            )
                            structured_rates = _structured_growth_rates(content, match)
                            if structured_rates is not None:
                                growth_rates = [
                                    (basis, value)
                                    for basis, value, growth_period in structured_rates
                                    if periods_equivalent(growth_period, fact_period)
                                ]
                            elif (
                                str(metadata.get("content_type", "")).casefold() == "table"
                                and len(periods) > 1
                            ):
                                # Multi-period financial rows need an explicit
                                # labelled comparison cell before a rate can be
                                # assigned to a period. Proximity alone is not
                                # enough to associate a YoY/QoQ value.
                                growth_rates = []
                            else:
                                growth_rates = list(_reported_growth_rates(evidence_text))
                                if fact_metric_id == "revenue":
                                    existing_bases = {basis for basis, _ in growth_rates}
                                    growth_rates.extend(
                                        (basis, value)
                                        for basis, value in _reported_growth_rates(
                                            _metric_clause(content, match)
                                        )
                                        if basis not in existing_bases
                                    )
                            facts.extend(
                                _growth_fact(base_fact, growth_basis, growth_value, evidence_text)
                                for growth_basis, growth_value in growth_rates
                            )
                    if facts and facts[-1].metric_id == metric_id and facts[-1].chunk_id == chunk_id:
                        break
        return cls(facts)

    def lookup(
        self,
        *,
        company: str | None = None,
        metric_id: str | None = None,
        period: str | None = None,
        growth_basis: str | None = None,
        dimension: str | None = None,
        category: str | None = None,
    ) -> tuple[FinancialFact, ...]:
        """按公司、指标、期间及可选表格维度筛选事实；未指定维度表示不增加该项约束。"""
        wanted_company = canonical_company(company or "") if company else None
        results = tuple(
            fact
            for fact in self.facts
            if (wanted_company is None or fact.company == wanted_company)
            and (metric_id is None or fact.metric_id == metric_id)
            and fact.growth_basis == growth_basis
            and (dimension is None or fact.dimension == dimension)
            and (category is None or fact.category == category)
            and (
                period is None
                or periods_equivalent(fact.fact_period, period)
                or periods_equivalent(fact.table_column_period, period)
            )
        )
        # Source-backed statement observations outrank weaker narrative
        # extraction when both describe the same requested metric.
        return tuple(sorted(results, key=lambda fact: 0 if fact.source_kind == "FINANCIAL_STATEMENT" else 1))

    def get(self, fact_id: str) -> FinancialFact | None:
        return self._by_id.get(fact_id)

    def companies(self) -> tuple[str, ...]:
        return tuple(dict.fromkeys(fact.company for fact in self.facts if fact.company))

    def as_dict(self) -> list[dict[str, object]]:
        return [
            fact.provenance | {"value": str(fact.normalized_value), "unit": fact.unit, "currency": fact.currency}
            for fact in self.facts
        ]

    def prompt_context(self, facts: Iterable[FinancialFact] | None = None) -> str:
        lines = ["VERIFIED FINANCIAL FACT LEDGER", "Only these structured facts may supply financial numbers."]
        visible_facts = tuple(self.facts if facts is None else facts)
        companies = tuple(dict.fromkeys(fact.company for fact in visible_facts if fact.company))
        for company in companies:
            lines.append(f"\nCOMPANY PARTITION: {company}")
            for fact in visible_facts:
                if fact.company != company:
                    continue
                lines.append(
                    f"- fact_id={fact.fact_id}; metric_id={fact.metric_id}; value={fact.normalized_value} "
                    f"{fact.currency or ''}; fact_period={fact.fact_period or 'undated'}; "
                    f"dimension={fact.dimension or 'unspecified'}; category={fact.category or 'unspecified'}; "
                    f"document={fact.document}; page={fact.page}; chunk_id={fact.chunk_id}"
                )
        return "\n".join(lines)


def _estimated_context_tokens(text: str) -> int:
    """Conservatively estimate mixed English/Chinese prompt token usage.

    A tokenizer is intentionally not imported into the retrieval path.  A
    one-character upper bound is deliberately conservative for mixed CJK/
    English prompt text and leaves room for the surrounding prompt template.
    The bound prevents an 8192-context local model from receiving an oversized
    request even when its tokenizer differs from the backend's estimator.
    """
    return max(1, len(str(text or "")))


def build_evidence_first_context(
    question: str,
    evidence: Iterable[Evidence],
    plan: object | None = None,
    *,
    max_context_tokens: int | None = None,
) -> tuple[str, FactLedger]:
    """Render verified facts followed by bounded, relevance-first evidence.

    ``max_context_tokens`` is optional to preserve the historical unlimited
    behaviour for providers with large context windows.  When set, required
    fact chunks are retained first and narrative chunks are added in their
    original order until the budget is reached.  The ledger remains complete,
    so dropping narrative overflow cannot drop a required numeric fact.
    """

    items = list(evidence)
    ledger = FactLedger.from_evidence(items)
    visible_ledger_facts: tuple[FinancialFact, ...] | None = None
    if max_context_tokens is not None and plan is not None:
        required_specs = getattr(plan, "required", ())
        selected_facts: list[FinancialFact] = []
        seen_fact_ids: set[str] = set()
        for spec in required_specs:
            for fact in ledger.lookup(
                company=getattr(spec, "company", None),
                metric_id=getattr(spec, "metric_id", None),
                period=getattr(spec, "period", None),
                growth_basis=getattr(spec, "growth_basis", None),
            ):
                if fact.fact_id not in seen_fact_ids:
                    selected_facts.append(fact)
                    seen_fact_ids.add(fact.fact_id)
        visible_ledger_facts = tuple(selected_facts)
    sections = [ledger.prompt_context(visible_ledger_facts)]
    if plan is not None and hasattr(plan, "prompt_context"):
        sections.append(plan.prompt_context(ledger))
    sections.append("\nRELEVANT NARRATIVE EVIDENCE")
    if max_context_tokens is None:
        selected = items
    else:
        budget = max(512, int(max_context_tokens))
        reserved_tokens = _estimated_context_tokens("\n\n".join(sections))
        remaining = max(0, budget - reserved_tokens)
        required_chunk_ids: set[str] = set()
        required_specs = getattr(plan, "required", ()) if plan is not None else ()
        for spec in required_specs:
            for fact in ledger.lookup(
                company=getattr(spec, "company", None),
                metric_id=getattr(spec, "metric_id", None),
                period=getattr(spec, "period", None),
                growth_basis=getattr(spec, "growth_basis", None),
            ):
                if fact.chunk_id:
                    required_chunk_ids.add(str(fact.chunk_id))
        priority = [
            item for item in items
            if str(item.metadata.get("chunk_id", "")) in required_chunk_ids
        ]
        rest = [item for item in items if item not in priority]
        selected = []
        for item in (*priority, *rest):
            rendered = (
                f"[Evidence {len(selected) + 1}]\nSource: {item.source}\n"
                f"Chunk: {item.metadata.get('chunk_id', '')}\n{item.content}"
            )
            cost = _estimated_context_tokens(rendered)
            if cost <= remaining:
                selected.append(item)
                remaining -= cost
                continue
            if not selected and remaining > 32:
                # Keep a bounded prefix if one very large chunk is the only
                # available evidence; structured facts are already above it.
                prefix_chars = max(64, remaining * 2)
                selected.append(
                    replace(item, content=str(item.content or "")[:prefix_chars])
                )
                remaining = 0
            if remaining <= 0:
                break
        # If the ledger/plan consumed the whole budget, retain no narrative
        # rather than emitting an over-budget prompt.
    for index, item in enumerate(selected, 1):
        sections.append(
            f"[Evidence {index}]\nSource: {item.source}\nChunk: {item.metadata.get('chunk_id', '')}\n{item.content}"
        )
    return "\n\n".join(sections), ledger
