from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

from agent.planning import ComplexityLevel, TaskType

# =========================
# Step Types
# =========================


class StepType(str, Enum):
    RETRIEVE = "retrieve"
    COMPARE = "compare"
    SYNTHESIS = "synthesis"
    TOOL_CALL = "tool_call"
    REASONING = "reasoning"


# =========================
# Step Status
# =========================


class StepStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


# =========================
# Plan Step
# =========================


@dataclass
class PlanStep:
    """
    One executable task in an execution plan.
    """

    step_id: int

    step_type: StepType

    description: str

    query: Optional[str] = None

    company: Optional[str] = None

    document_ids: List[str] = field(default_factory=list)

    depends_on: List[int] = field(default_factory=list)

    parameters: Dict[str, Any] = field(default_factory=dict)

    status: StepStatus = StepStatus.PENDING

    result: Any = None

    tool_name: Optional[str] = None


# =========================
# Execution Plan
# =========================


@dataclass
class ExecutionPlan:
    """
    Agent execution plan generated by Query Planner.
    """

    intent: str

    original_query: str

    tasks: List[PlanStep] = field(default_factory=list)

    metadata: Dict[str, Any] = field(default_factory=dict)

    # Planner information
    task_type: TaskType | None = None

    complexity: ComplexityLevel | None = None

    complexity_score: float = 0.0

    estimated_tokens: int = 0

    estimated_latency_ms: int = 0

    estimated_cost: float = 0.0

    planner_reason: str = ""

    complexity_reason: str = ""

    planner_version: str = "rule-v1"
