"""Deterministic company-report period and metric hints.

The filename is not authoritative for a financial period: a report can contain
several comparative quarters (the Tesla Q4/FY2025 update is one example).
These helpers therefore recognise period labels in the extracted text and in
the user query, and return stable keys used only for retrieval constraints.
"""

from __future__ import annotations

import re

from core.financial_grounding import extract_normalized_numbers

_QUARTER = r"(?P<quarter>[1-4])"
_YEAR = r"(?P<year>20\d{2})"

_PERIOD_PATTERNS = (
    # Financial releases commonly abbreviate fiscal years in table headers
    # (``Q1 FY27``) or spell them out (``Q1 Fiscal 2027``). Keep the fiscal
    # marker so these are not confused with calendar-quarter labels.
    re.compile(
        rf"\bQ{_QUARTER}\s*[-/_]?\s*(?P<fiscal>FY|Fiscal)?\s*"
        r"(?P<year>20\d{2}|\d{2})\b",
        re.IGNORECASE,
    ),
    # Require the separator for reverse labels such as ``2025-Q2``.  Allowing
    # it to be absent made a forward sequence (``Q4-2024 Q1-2025``) overlap as
    # the phantom reverse label ``2024 Q1``.
    re.compile(rf"\b{_YEAR}\s*[-/]\s*Q{_QUARTER}\b", re.IGNORECASE),
    re.compile(
        rf"\b(?:first|1st|second|2nd|third|3rd|fourth|4th)\s+quarter"
        rf"\s+(?:of\s+)?(?:(?:fiscal(?:\s+year)?|fy)\s*)?{_YEAR}\b",
        re.IGNORECASE,
    ),
    re.compile(
        rf"\b(?:first|1st|second|2nd|third|3rd|fourth|4th)\s+"
        rf"(?:fiscal|fy)\s+quarter\s+(?:of\s+)?{_YEAR}\b",
        re.IGNORECASE,
    ),
)
_QUARTER_WORDS = {
    "first": 1,
    "1st": 1,
    "second": 2,
    "2nd": 2,
    "third": 3,
    "3rd": 3,
    "fourth": 4,
    "4th": 4,
}
_CJK_PERIOD = re.compile(r"(?P<year>20\d{2})\s*(?:年\s*)?(?:财年\s*)?(?:第)?(?P<quarter>[一二三四])季度")
_EXPLICIT_FISCAL_YEAR = (
    re.compile(r"\bFY\s*[-_/]?\s*(?P<year>20\d{2}|\d{2})\b", re.IGNORECASE),
    re.compile(
        r"\b(?:full[- ]year|annual|year ended|twelve months ended)"
        r"[\w\s,./-]{0,48}(?P<year>20\d{2})\b",
        re.IGNORECASE,
    ),
    re.compile(r"\b(?:fiscal\s+(?:year\s+)?)20(?P<short_year>\d{2})\b", re.IGNORECASE),
    # Some extracted Chinese annual-report titles contain the duplicated
    # marker ``2025 年年度报告``. This remains an explicit fiscal-year label.
    re.compile(r"(?P<year>20\d{2})\s*年\s*年度"),
    re.compile(r"(?P<year>20\d{2})\s*(?:财年|年度|全年)"),
)
_DURATION_TABLE = re.compile(
    r"\b(?:three|six|nine|twelve)\s+months?\s+(?:ended|ending)\b|"
    r"\b(?:quarter|quarterly)\s+ended\b|季度截至|季度结束",
    re.IGNORECASE,
)


def _normalize_quarter_marker(value: str) -> str:
    """Normalize fiscal-year marker spelling without changing quarter/year."""

    return value.upper().replace("-", "_").replace("_FY", "_")

_METRIC_ALIASES = (
    ("data_center", ("data center", "datacenter", "data centre", "datacentre", "数据中心")),
    # Natural-language questions frequently use the plural/short form
    # ("margins", "profit margin", "毛利") rather than the exact filing
    # label.  Treat these as retrieval hints, never as a hard exclusion.
    (
        "gross_margin",
        (
            "gross margin", "gross margins", "profit margin", "profitability",
            "毛利率", "毛利",
        ),
    ),
    ("automotive_gross_margin", ("automotive gross margin", "汽车业务毛利率")),
    ("operating_margin", ("operating margin", "operating margins", "operating profit margin", "营业利润率")),
    ("revenue", ("revenue", "revenues", "net sales", "营收", "收入")),
    (
        "iphone_revenue",
        (
            "iphone®", "iphone net sales", "iphone revenue",
            "iphone 销售额", "iphone收入", "iphone 收入", "iphone销售额",
        ),
    ),
    ("products_revenue", ("products net sales", "products revenue", "产品净销售额", "产品收入")),
    ("mac_revenue", ("mac®", "mac net sales", "mac revenue", "mac销售额", "mac收入")),
    ("ipad_revenue", ("ipad®", "ipad net sales", "ipad revenue", "ipad销售额", "ipad收入")),
    (
        "wearables_revenue",
        (
            "wearables, home and accessories",
            "wearables net sales",
            "wearables revenue",
            "可穿戴设备、家居和配件",
        ),
    ),
    ("net_income", ("net income", "net profit", "净利润")),
    ("operating_income", ("operating income", "营业利润")),
    (
        "free_cash_flow",
        ("free cash flow", "fcf", "自由现金流"),
    ),
    (
        "operating_cash_flow",
        (
            "net cash provided by operating activities",
            "cash generated by operating activities",
            "operating cash flow",
            "经营活动现金流",
            "经营活动产生的现金流",
        ),
    ),
    ("cash_paid_for_taxes", ("cash paid for income taxes", "cash paid for taxes", "所得税支付现金", "支付的所得税")),
    ("cash_flow", ("cash flow", "现金流")),
    ("eps", ("eps", "earnings per share", "每股收益")),
    ("automotive", ("automotive", "汽车业务")),
    ("services", ("services", "service-related", "service business", "服务业务", "服务相关")),
    (
        "energy_revenue",
        (
            "energy generation and storage revenue",
            "energy revenue",
            "能源发电与储能收入",
            "能源收入",
        ),
    ),
    ("energy", ("energy generation", "储能", "能源")),
)


def extract_periods(text: str) -> tuple[str, ...]:
    """Return normalized quarter keys present in *text*, preserving order."""

    periods: list[str] = []
    seen: set[str] = set()

    def add(quarter: int, year: str, fiscal: bool = False) -> None:
        key = f"Q{quarter}_FY{year}" if fiscal else f"Q{quarter}_{year}"
        if key not in seen:
            seen.add(key)
            periods.append(key)

    for match in _PERIOD_PATTERNS[0].finditer(text):
        year = match.group("year")
        if len(year) == 2:
            year = f"20{year}"
        add(int(match.group("quarter")), year, bool(match.group("fiscal")))
    for match in _PERIOD_PATTERNS[1].finditer(text):
        add(int(match.group("quarter")), match.group("year"))
    for pattern in _PERIOD_PATTERNS[2:]:
        for match in pattern.finditer(text):
            words = match.group(0).casefold().split()
            quarter = next((value for word, value in _QUARTER_WORDS.items() if word in words), None)
            if quarter is not None:
                match_lower = match.group(0).casefold()
                add(
                    quarter,
                    match.group("year"),
                    "fiscal" in match_lower or "fy" in match_lower,
                )
    for match in _CJK_PERIOD.finditer(text):
        add("一二三四".index(match.group("quarter")) + 1, match.group("year"), "财年" in match.group(0))
    return tuple(periods)


def extract_annual_periods(text: str) -> tuple[str, ...]:
    """Return annual fiscal periods without treating bare years as quarters.

    Explicit annual labels are accepted directly. A sequence of two or more
    year-only table headers is also an annual comparative table unless its
    header identifies quarter/YTD duration columns (for example Apple's
    ``Three Months Ended`` / ``Six Months Ended`` statements).
    """

    value = str(text or "")
    periods: list[str] = []
    seen: set[str] = set()

    def add(year: str) -> None:
        normalized = f"20{year}" if len(year) == 2 else year
        key = f"FY{normalized}"
        if key not in seen:
            seen.add(key)
            periods.append(key)

    for pattern in _EXPLICIT_FISCAL_YEAR:
        for match in pattern.finditer(value):
            prefix = value[max(0, match.start() - 24) : match.start()]
            if re.search(r"\bQ[1-4]\s*[-/_]?\s*(?:FY|Fiscal)?\s*$", prefix, re.IGNORECASE):
                # The FY marker belongs to a quarter label (Q1 FY2027), not a
                # separate annual-period claim.
                continue
            add(match.groupdict().get("year") or match.group("short_year"))

    if re.search(r"\btwelve\s+months?\s+(?:ended|ending)\b", value, re.IGNORECASE):
        for year in dict.fromkeys(re.findall(r"\b(20\d{2})\b", value)):
            add(year)
        return tuple(periods)
    if periods or _DURATION_TABLE.search(value):
        return tuple(periods)

    annual_heading = re.search(
        r"financial\s+summary|annual\s+financial\s+(?:summary|results?)|"
        r"full[- ]year\s+(?:financial\s+)?(?:summary|results?)|年度财务(?:摘要|业绩)|全年财务",
        value,
        re.IGNORECASE,
    )
    if extract_periods(value) and not annual_heading:
        return ()
    scope = value[annual_heading.start() :] if annual_heading else value
    years = list(dict.fromkeys(re.findall(r"\b(20\d{2})\b", scope)))
    if len(years) >= 2:
        for year in years:
            add(year)
    return tuple(periods)


def extract_metrics(text: str) -> tuple[str, ...]:
    """Return canonical metric labels explicitly mentioned in *text*."""

    lowered = text.casefold()
    matched = {
        canonical for canonical, aliases in _METRIC_ALIASES if any(alias.casefold() in lowered for alias in aliases)
    }
    coordinated_margins = re.search(
        r"\bgross\s+and\s+operating\s+margins?\b|毛利(?:率)?\s*(?:和|及|与)\s*营业利润率",
        lowered,
    )
    if coordinated_margins:
        matched.update(("gross_margin", "operating_margin"))
    elif re.search(r"\bmargins?\b|利润率", lowered) and not re.search(
        r"\bgross\s+(?:profit\s+)?margins?\b|\boperating\s+(?:profit\s+)?margins?\b|毛利率|营业利润率",
        lowered,
    ):
        # An unqualified request for "margins" covers both common margins;
        # do not silently turn it into a gross-margin-only filter.
        matched.update(("gross_margin", "operating_margin"))
    if "automotive_gross_margin" in matched:
        matched.discard("gross_margin")
        matched.discard("automotive")
    return tuple(canonical for canonical, _ in _METRIC_ALIASES if canonical in matched)


def query_filters(question: str) -> dict[str, str]:
    """Build safe retrieval filters from explicit query constraints."""

    filters: dict[str, str] = {}
    periods = extract_periods(question)
    if len(periods) == 1:
        filters["period"] = periods[0]
    elif not periods:
        annual_periods = extract_annual_periods(question)
        if len(annual_periods) == 1:
            filters["period"] = annual_periods[0]
    # A multi-period query (growth, comparison, prior-year) needs evidence from
    # each named period. Selecting only the first period silently removes the
    # comparison operand before retrieval/grounding. In that case period
    # scope remains claim-level and is validated against each answer clause.
    metrics = extract_metrics(question)
    specific_metrics = tuple(metric for metric in metrics if metric not in {"revenue"})
    if len(specific_metrics) == 1:
        filters["metric"] = specific_metrics[0]
    elif len(metrics) == 1:
        filters["metric"] = metrics[0]
    return filters


def matches_filter(content: str, metadata: dict, key: str, expected: str) -> bool:
    """Match a semantic filter against metadata, with content fallback."""

    if key == "period":
        # A chunk may carry both the filing/document period and the periods
        # represented by a comparative table.  Prefer explicit row/column
        # metadata when available; a filename or document quarter alone is
        # not authoritative for a claim period.
        for field in ("evidence_row_period", "row_period"):
            value = metadata.get(field)
            if isinstance(value, (list, tuple, set)) and expected in value:
                return True
            if isinstance(value, (list, tuple, set)) and value:
                return False
            if isinstance(value, str) and expected in {
                part.strip() for part in value.replace(",", "|").split("|") if part.strip()
            }:
                return True
            if isinstance(value, str) and value.strip():
                return False
        content_periods = extract_periods(content)
        if content_periods:
            # An explicit quarter in this chunk outranks document-level or
            # cached period metadata.  In particular, a Q2 guidance paragraph
            # must not inherit a stale Q1 quarter copied from its filename or
            # parent document.
            if expected in content_periods:
                return True
            metadata_quarter = str(metadata.get("quarter", "")).replace("-", "_")

            # Some reports spell a quarter as ``Q2 FY2026`` in a table but
            # ``Q2 2026`` in their filing header. Treat those spellings as the
            # same only when the independently extracted document period
            # exactly matches the unmarked request; never use this alias to
            # override a different explicit quarter in the chunk.
            metadata_matches = (
                metadata_quarter
                and _normalize_quarter_marker(metadata_quarter)
                == _normalize_quarter_marker(expected)
            )
            content_matches = any(
                _normalize_quarter_marker(period)
                == _normalize_quarter_marker(expected)
                for period in content_periods
            )
            if metadata_matches and content_matches:
                return True
            return False
        annual_periods = extract_annual_periods(
            f"{metadata.get('table_context', '')}\n{metadata.get('periods', '')}\n{content}"
        )
        if expected.upper().startswith("FY"):
            if expected.upper() in annual_periods:
                return True
            # Narrative disclosures inherit their filing's year, not a
            # financial observation period. Require two agreeing source hints
            # and no explicit content period. Never apply this to table facts.
            source = str(metadata.get("source", ""))
            year = expected.upper()[2:]
            return bool(
                metadata.get("content_type") == "narrative"
                and not content_periods
                and re.fullmatch(r"20\d{2}", year)
                and str(metadata.get("quarter", "")) == year + "-12-31"
                and re.search(re.escape(year) + r"\s*年?\s*(?:年度报告|年报)", source)
            )
        if expected.upper().startswith("Q") and annual_periods:
            # A filing-level Q4 label does not turn a year-column summary into
            # a fourth-quarter result. Preserve annual evidence for annual
            # requests only.
            return False
        values = str(metadata.get("periods", ""))
        metadata_periods = tuple(
            part.strip() for part in values.replace(",", "|").split("|") if part.strip()
        )
        if metadata_periods:
            if expected in metadata_periods:
                return True
            if expected.upper().startswith("Q"):
                normalized_expected = _normalize_quarter_marker(expected)
                return any(
                    _normalize_quarter_marker(period) == normalized_expected
                    for period in metadata_periods
                    if period.upper().startswith("Q")
                )
            return False
        table_period_values = metadata.get("table_periods", "")
        if isinstance(table_period_values, (list, tuple, set)):
            table_periods = tuple(str(value).strip() for value in table_period_values if str(value).strip())
        else:
            table_periods = tuple(
                part.strip()
                for part in str(table_period_values).replace(",", "|").split("|")
                if part.strip()
            )
        if table_periods:
            return (
                metadata.get("content_type") == "table"
                and len(table_periods) == 1
                and expected in table_periods
            )
        table_context_periods = extract_periods(str(metadata.get("table_context", "") or ""))
        if table_context_periods:
            # Some parsers separate a trusted, single-period table header from
            # its bound row. Use that local structure for retrieval. A
            # comparative header with several periods is not enough to bind a
            # value to one column unless the row itself carries the period.
            return (
                metadata.get("content_type") == "table"
                and len(table_context_periods) == 1
                and expected in table_context_periods
            )
        # A parser may keep the filing quarter in metadata while splitting a
        # single-period metric row away from its table header.  Accept that
        # issuer-backed document-period hint only when neither the chunk nor
        # its local table header exposes a period. Fiscal marker spelling
        # variants (``Q2_2026`` and ``Q2_FY2026``) represent the same quarter,
        # but the quarter/year must still match exactly. Comparative tables
        # still require row/column evidence.
        metadata_quarter = str(metadata.get("quarter", "")).replace("-", "_")
        if metadata_quarter and _normalize_quarter_marker(metadata_quarter) == _normalize_quarter_marker(expected):
            return True
        return False
    if key == "metric":
        if expected == "cash_flow":
            lowered = content.casefold()
            if not any(
                marker in lowered
                for marker in (
                    "cash generated by operating activities",
                    "operating cash flow",
                    "经营活动产生的现金流",
                )
            ):
                return False
            return True
        values = str(metadata.get("metrics", ""))
        if expected in values.split("|"):
            return True
        return expected in extract_metrics(content)
    return metadata.get(key) == expected


def has_explicit_period_conflict(content: str, metadata: dict, expected: str) -> bool:
    """Return whether evidence explicitly identifies a different period.

    Missing period metadata is not a conflict: it remains eligible for
    semantic ranking. Explicit period text in the chunk is stronger than a
    document/filename hint, so adjacent-quarter guidance cannot enter a
    single-period context merely because its parent PDF is for the requested
    quarter. Chunks mentioning the requested period alongside another period
    remain eligible for claim-level grounding.
    """

    content_periods = extract_periods(content)
    if content_periods:
        if expected in content_periods:
            return False
        metadata_quarter = str(metadata.get("quarter", "")).replace("-", "_")
        if (
            metadata_quarter
            and _normalize_quarter_marker(metadata_quarter) == _normalize_quarter_marker(expected)
            and any(
                _normalize_quarter_marker(period) == _normalize_quarter_marker(expected)
                for period in content_periods
            )
        ):
            return False
        return True

    for field in ("evidence_row_period", "row_period"):
        value = metadata.get(field)
        if isinstance(value, (list, tuple, set)):
            periods = {str(item).strip() for item in value if str(item).strip()}
        else:
            periods = {
                part.strip()
                for part in str(value or "").replace(",", "|").split("|")
                if part.strip()
            }
        if periods:
            return expected not in periods
    return False


def period_scoped_row_numbers(
    content: str,
    expected_period: str,
    metric: str | None = None,
) -> list:
    """Extract only the values from a comparative table's requested column.

    Financial filings often put Q1/Q2/Q3/Q4 values in one chunk.  Returning
    every number in that chunk makes a Q2 claim appear supported by a Q4
    value.  This conservative helper maps a detected header to the metric row
    and returns the matching column; callers fall back to the full chunk only
    when no structured row can be proven.
    """

    headers: list[tuple[str, int]] = []
    for match in re.finditer(
        r"\bQ([1-4])\s*[-/]?\s*(?:FY\s*)?(20\d{2})\b",
        content,
        re.IGNORECASE,
    ):
        fiscal = "FY" in match.group(0).upper()
        key = f"Q{match.group(1)}_{'FY' if fiscal else ''}{match.group(2)}"
        headers.append((key, match.start()))
    # A single period mention in narrative text is not a table header.  Row
    # scoping requires at least two period columns to establish a column map.
    if len(headers) < 2:
        return []
    target_index = next(
        (index for index, (key, _) in enumerate(headers) if key == expected_period),
        None,
    )
    if target_index is None:
        return []

    # A metric label is required for row-level disambiguation.  Specific
    # aliases are tried first so "automotive revenue" does not match the
    # broader "revenue" row.
    aliases = {
        "revenue": ("total revenues", "total revenue", "net sales", "revenues"),
        "automotive_revenue": ("total automotive revenues", "automotive revenue"),
        "services_revenue": ("services and other revenue", "services revenue"),
        "energy_revenue": (
            "energy generation and storage revenue",
            "energy generation and storage",
            "energy revenue",
        ),
        "mac_revenue": ("mac net sales", "mac revenue", "mac®"),
        "ipad_revenue": ("ipad net sales", "ipad revenue", "ipad®"),
        "wearables_revenue": (
            "wearables, home and accessories",
            "wearables net sales",
            "wearables revenue",
        ),
        "products_gross_margin": (
            "products gross margin", "metric: products", "产品毛利率",
        ),
        "services_gross_margin": (
            "services gross margin", "metric: services", "服务毛利率",
        ),
        "data_center_revenue": ("data center revenue", "datacenter revenue"),
        "gross_margin": ("gross margin",),
        "automotive_gross_margin": ("automotive gross margin",),
        "net_income": ("net income", "net profit"),
        "operating_income": ("operating income", "income from operations"),
        "operating_cash_flow": (
            "net cash provided by operating activities",
            "cash generated by operating activities",
            "operating cash flow",
        ),
        "cash_flow": ("cash generated by operating activities", "operating cash flow"),
    }
    wanted = aliases.get(metric or "", ())
    if not wanted:
        return []
    lowered = content.casefold()
    for alias in wanted:
        start = lowered.find(alias.casefold())
        if start < 0:
            continue
        # Stop before a likely next row/section.  The numeric parser is
        # intentionally used on a bounded segment to avoid collecting all
        # table values from the chunk.
        segment = content[start : start + 500]
        values = extract_normalized_numbers(segment)
        # The first values may be labels such as a year or a unit; retain the
        # table's column count and select the requested column.
        if len(values) > target_index:
            return [values[target_index]]
    return []
